### ISSUE TITLE
`import` query parameter doesn't work in Safari

### ISSUE THREAD

**Issue by brhou** [swagger-api/swagger-editor#644] opened 2015-09-14 18:41 UTC
Using Chrome and Firefox to import a `yaml` or `json` through the url works but using the same url in Safari errors.

Example url = [http://editor.swagger.io/#/?import=http://petstore.swagger.io/v2/swagger.json](http://editor.swagger.io/#/?import=http://petstore.swagger.io/v2/swagger.json)

When I load this url in Chrome or Firefox, it imports successfully. When I use Safari, I get this error message in the UI:

![screen shot 2015-09-14 at 11 31 45 am](https://cloud.githubusercontent.com/assets/8788114/9858309/d5c2ae8e-5ad4-11e5-88ce-86f94c7be9f7.png)

And this message in the console:
![screen shot 2015-09-14 at 11 31 52 am](https://cloud.githubusercontent.com/assets/8788114/9858340/0cc362e8-5ad5-11e5-8c73-f0b57f26981b.png)

Fails the same way using a local instance of swagger-editor.

**Comment by mohsen1** [comment] 2015-09-14 18:50
Duplicate of https://github.com/swagger-api/swagger-editor/issues/636

**Closed** 2015-09-15 23:31 UTC
Labels: duplicate, wont-fix
