### ISSUE TITLE
'Try this operation' stops working after clicking 'List all operations'

### ISSUE THREAD

**Issue by Ra1ny** [swagger-api/swagger-editor#928] opened 2016-05-11 14:39 UTC
![swagger-bug](https://cloud.githubusercontent.com/assets/3930939/15184440/152e4162-178d-11e6-8212-5d86e20c2dbb.png)

For the following spec:
```
swagger: '2.0'

info:
  version: "1.0.0"
  title: API
  
paths:
  /api-path:
    post:
      description: xxx
      parameters:
        - 
          name: body
          in: body
          description: Request body
          required: true
          schema:
            type: object
            properties:
              string: 
                type: string
      responses:
        200:
          description: Success
```

Steps to reproduce:
1. Write the above spec into a file
2. `File` -> `Import file...` -> `Choose file` and select the YAML file created in the first step.
3. Click `List all operations`
4. Click on the request header `PATCH /api-path`
5. Click `Try this operation` button

The try-it section is generated correctly if you avoid clicking on 'List all operations'. Seems to only occur if the body parameter's schema contains properties, regardless of the type.

**Comment by saharj** [comment] 2016-05-11 19:40
I don't get it. When you click on `List all operations`, all operations get folded and you won't be able to see or use the button. So how do you go from step 2 to 3?

**Comment by Ra1ny** [comment] 2016-05-12 07:52
I updated the instructions.

**Comment by saharj** [comment] 2016-05-13 00:01
I don't see this issue. Please make sure you build from `master`.

**Comment by Ra1ny** [comment] 2016-05-16 13:54
I cannot build from `master` at this moment. Instead I downloaded the static files. This also happens for me at http://editor.swagger.io/

**Comment by Ra1ny** [comment] 2016-05-18 13:59
I added extra steps to the instructions. Try importing the file few times if the bug doesn't happen, as it seems to occur after second import. I can make a video, if that would be of any help.

**Comment by saharj** [comment] 2016-08-11 23:29
I still am not able to reproduce this issue, so I'm going to close it. Please feel free to let us know if you still have this problem

**Closed by saharj** 2016-08-11 23:29 UTC
Labels: question
