### ISSUE TITLE
Very slow edition when handling large yaml spec (about 3000 lines)

### ISSUE THREAD

**Issue by danielm64** [swagger-api/swagger-editor#503] opened 2015-06-18 12:27 UTC
We handle some large YAML files due to a large number of methods and verbose documentation.
When editing such large files, the editor is very very slow... even if the preview is disabled.
Using Firefox 38.0.5 and Chrome 43.0.2357.124.

**Comment by mohsen1** [comment] 2015-06-18 17:09
I'm aware of this and one of our goals for the next release is to make it more performant on larger spec files.

**Comment by mohsen1** [comment] 2015-06-27 17:47
Duplicate of #448

**Closed by mohsen1** 2015-06-27 17:47 UTC
Labels: enhancement
