### ISSUE TITLE
Error Dialog displays for valid content in #289 still happening

### ISSUE THREAD

**Issue by Syzygy24** [swagger-api/swagger-editor#540] opened 2015-07-08 19:49 UTC
https://github.com/swagger-api/swagger-editor/issues/289

That issue was closed and reportedly fixed in December, but I am getting the same exact error using the swagger editor at editor.swagger.io. Has the online version not been updated with the fix?

**Comment by mohsen1** [comment] 2015-07-08 19:53
Yes, this is duplicate of #539 and #289 as result of https://github.com/swagger-api/swagger-editor/commit/03e0a18b01c4e517e8934833712807739272c286. I don't want to remove memoize call because it will introduce a lot of performance issues. I'll dig into it to fix it without losing memoize

**Closed by mohsen1** 2015-07-08 19:53 UTC
