### ISSUE TITLE
Editor fails to open JSON when using backend storage

### ISSUE THREAD

**Issue by AlexDobrolyubov** [swagger-api/swagger-editor#853] opened 2016-03-28 06:16 UTC
Hi Folks, I'm having problem with JSON backend storage. The editor is throwing an error that says:

```
options.definition must be either an object or a string
```

it seems the editor is unable to properly build schema downloaded from a local backend. Here are the editor settings:

```
    "useBackendForStorage": true,
    "backendEndpoint": "/editor-spec-storage",
    "backendThrottle": 200,
    "keyPressDebounceTime": 200,
    "useYamlBackend": false,
```

Here is what I'm getting in browser:

<img width="1437" alt="screen shot 2016-03-27 at 11 03 50 pm" src="https://cloud.githubusercontent.com/assets/3526747/14072140/b6fb2850-f471-11e5-9d18-403733c2ebbb.png">

**Comment by saharj** [comment] 2016-04-05 04:03
Possibly we haven't updated sway api in backend service

**Comment by pgrm** [comment] 2016-05-07 19:52
depending on your backend storage you could set `useYamlBackend` to true as a work around. This way you'd have yaml both ways and it works

**Comment by saharj** [comment] 2016-05-07 21:41
The `options.definition must be either an object or a string` error was from a discrepancy in API calls to Sway. It should be fixed now. Please let me know if you still have this issue.

**Comment by amritgre** [comment] 2016-08-03 02:24
I'm getting this exact same error now if I use Backend Endpoint. I just cloned the master from github last month. Version is 2.10.2

**Comment by saharj** [comment] 2016-08-03 22:49
@amritgre did you build after getting the latest? Also I recommend you don't build from source and use the published version either from npm or Docker.

**Comment by amritgre** [comment] 2016-08-03 23:27
@saharj I tried building after downloading but there is no difference. I need to use the editor so that every time I open editor, it downloads the swagger from import url passed as query parameter and then use that dynamic url for backend storage every time. npm_module seems like it's built around api projects. Would that work for what I want to do?
Thanks for replying Saharj

**Comment by saharj** [comment] 2016-08-05 15:27
@amritgre Can you please give us more details about the error you are getting? And a sample project that produces the error?

**Comment by rajbrt** [comment] 2016-08-29 08:51
Hello @saharj,
Backend implementation **works** if the **backend storage format is  .yaml** with the default json settings as follows  

"backendEndpoint": "http://localhost:3003/api/definition",
"useYamlBackend": true

But if the **useYamlBackend** is set to **false** and the **backend storage format is  .json** then getting the **error "options.definition must be either an object or a string".**

Have checked the code and the issue seems to be in the builder.js with the package js-yaml. 
1. If the backend file format is -.yaml-, then the js-yaml load function creates the proper json object as output
2. If the backend file format is -.json-, then the js-yaml load function outputs the string value as ["object","object"] which subsequently creates the issue.

Have attached the screenshots for reference 
1. SwaggerEditor_issue_ErrorPage.png - Editor error page
2. Swagger_Editor_Isseu_ConsoleLog.png - With console log of the output logging the flow from  backend to builder js inside the functions save(..), buildDocs(..) and commitNow(..) 

Don't know whether this is the expected behaviour for swagger editor to accepts only .yaml file as a backend storage.

Anywayz, Have got this working for me by using yaml as the backend storage. Just my analysis for reference.

Cheers,
Raj
![swagger_editor_isseu_consolelog](https://cloud.githubusercontent.com/assets/8401236/18046096/d5600422-6df3-11e6-9bc8-a1aa47fa37cf.png)
![swaggereditor_issue_errorpage](https://cloud.githubusercontent.com/assets/8401236/18046097/d5646e68-6df3-11e6-9676-3fd5bf3a120b.png)

**Comment by mikelohmann** [comment] 2016-12-01 18:51
Hi,

Thanks @rajbrt. According to your findings I was able to find a working solution for the problem. I could not just switch everything to yaml because in my (nodeJs) project we use swaggerize-express to serve and validate.

Therefore I created two files json and yaml formatted. The yaml file I use for the editor and the json file for everything else. After writing the yaml file with my own small controller I use yamljs to create json from it and just store it in the json file.

Not the best possible solution, but a good enough workaround until the issue will be solved someday.

```js
    const yamlSpecFile = 'path to the yaml file';
    const stream = fs.createWriteStream(yamlSpecFile);
    stream.on('finish', function () {
      try {
        const specfilecontent = fs.readFileSync(yamlSpecFile, 'utf-8');
        const specfileJsonContent = JSON.stringify(YAML.parse(specfilecontent, 10));
        const jsonFilePath = 'path to the json swagger file';
        fs.writeFileSync(jsonFilePath, specfileJsonContent);
      } catch(e) {
        console.log('Error parsing content', e);
      }
      res.end('ok');
    });
    req
      .pipe(stream);
```

**Comment by Tokeiito** [comment] 2016-12-07 08:25
I can confirm that this issue still exists in Version 2.10.3 which i'm using from docker. With backend enabled. yaml turned off. 

Workflow as follows:

backend service, simply accepts PUT/GET. With GET it reads file and returns it contents where PUT saves request body into file.

While examining requests sent by Editor i see that reading was succesfull, but after two requests GET, it does PUT request with 

![image](https://cloud.githubusercontent.com/assets/743137/20960003/cd228d7c-bc66-11e6-84bb-2ee1ffd38297.png)

And of course famous error `options.definition must be either an object or a string` is shown on editor, while editor screen is blank.

JS Error console shows following errors:

![image](https://cloud.githubusercontent.com/assets/743137/20960062/2b36eaa2-bc67-11e6-82e1-5728f0086bc7.png)

As YAML format is nuisance for big amounts of data it is not an option to switch to it.

**Comment by Tokeiito** [comment] 2016-12-07 09:12
Same issue is with 2.10.4

**Comment by Tokeiito** [comment] 2016-12-07 09:28
As this issue is closed without fix in codebase, i've opened new one. https://github.com/swagger-api/swagger-editor/issues/1128

**Comment by camsjams** [comment] 2017-03-30 17:38
Any status on this?

**Comment by webron** [comment] 2017-06-08 23:27
Current editor doesn't have this feature. We'll circle back if/when it's reintroduced to 3.X.

**Closed by webron** 2017-06-08 23:27 UTC
Labels: bug
