### ISSUE TITLE
options.definition is required (ERROR_THROWN_BY_SWAY_CODE:undefined)

### ISSUE THREAD

**Issue by Shyri** [swagger-api/swagger-editor#732] opened 2015-11-30 07:20 UTC
Hi,
I'm having trouble get Swagger Editor accepting my previous JSON files.

I found out it doesn't even work with same JSON exported from examples.

To reproduce it: just open pet store example. Click file -> Download JSON. Open the JSON file, copy all, go back to swagger editor, click file, paste JSON, and paste the copied json. I will show this error 

 Object
message:  "options.definition is required"
code:  "ERROR_THROWN_BY_SWAY_CODE:undefined"

Thanks!

**Comment by webron** [comment] 2015-11-30 19:41
Which version of the editor do you use to produce that error?

**Comment by Shyri** [comment] 2015-11-30 20:14
The one available at http://editor.swagger.io/#/
Version 2.9.8

Thanks!

**Comment by Shyri** [comment] 2015-12-01 06:20
Yestarday I wasn't able to click the "Import" button after pasting. Now I can click it, it still shows up the error but at least I can import and continue working.

**Comment by webron** [comment] 2015-12-01 07:20
Looks like a duplicate of #668.

**Comment by saharj** [comment] 2016-01-26 04:35
Do you still have this issue? I can not reproduce it.

**Closed** 2016-04-28 05:03 UTC
Labels: bug, duplicate, help wanted
