### ISSUE TITLE
Source Code Pro fonts are getting 404 error in development mode

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#680] opened 2015-10-02 17:58 UTC
This is an artifact of #667. We need to add a proxy in connect task that serves fonts from bower_components folder. 
We should also install font-awesome, [open-sans](https://github.com/sheabunge/open-sans) and Bootstrap fonts from Bower and use [this service](http://www.cardinalsolutions.com/blog/2015/05/google-fonts-bower-proxy) for Droid Sans. With all of that we should not have any hardcoded fonts in the source code.

**Comment by warrichrepos** [comment] 2015-12-30 21:17
How do I fix this issue? Can't edit because of cursor placement is not correct. Thanks in advance.

downloadable font: download failed (font-family: "Source Code Pro" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://localhost:9000/styles/WOFF2/TTF/SourceCodePro-Regular.ttf.woff2

**Comment by saharj** [comment] 2016-02-06 23:34
Duplicate of #805

**Closed by saharj** 2016-02-06 23:34 UTC
Labels: enhancement
