### ISSUE TITLE
Unable to build swagger-editor

### ISSUE THREAD

**Issue by edwinanto2003** [swagger-api/swagger-editor#809] opened 2016-02-03 22:40 UTC
Hello,
I am not able to build swagger-editor locally. I tried in both Windows 7 as well as Ubuntu systems. 
The npm start command  stops at the following:
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/Benvie/harmony-collections.git", exit code of #128 fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am also attaching the log file 
[npm-debug-log.txt](https://github.com/swagger-api/swagger-editor/files/116526/npm-debug-log.txt)

**Comment by saharj** [comment] 2016-02-06 18:06
It's a duplicate of #743

**Closed by saharj** 2016-02-06 18:06 UTC
