### ISSUE TITLE
version format generates error

### ISSUE THREAD

**Issue by jehrlich** [swagger-api/swagger-editor#857] opened 2016-04-03 14:14 UTC
This code, slightly edited from the minimal example 
```
---
swagger: '2.0'
info:
  version: 1.2
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK

```
generates this error

Collapse
```
✖ Swagger Error
A semantic version number of the API.
Jump to line 3
Details
 Object
code:  "INVALID_TYPE"
message:  "Expected type string but found type number"
 path: Array [2]
description:  "A semantic version number of the API."
level: 900
type:  "Swagger Error"
lineNumber: 3
```

which can be resolved by adding a single . to the version number.  I don't believe this behavior is wanted or documented.

```
---
swagger: '2.0'
info:
  version: 1.2.
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK

```

Worse, when additional code is entered the error points to another line, misleading the poor victim (me) into all kinds of unusual hypotheses. I can reproduce the error by pasting the above code into http://editor.swagger.io/#/ and deleting the dot -> 1.2

I appreciate your work.

**Comment by fehguy** [comment] 2016-04-03 14:31
It actually is documented. Version is a string, and should be quoted to avoid automatic conversion to a number

**Comment by jehrlich** [comment] 2016-04-03 15:06
OK. It's not quoted in the example minimal.yaml.

```
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
```

**Comment by saharj** [comment] 2016-04-03 18:53
This is a duplicate of #733

**Closed by saharj** 2016-04-03 18:53 UTC

**Comment by fehguy** [comment] 2016-04-03 18:56
@jehrlich if a string can be implicitly converted to a number, it will be treated as such.  A string of `0.0.0` can _not_ be converted into a number and is therefore treated as a string.  I understand it can be confusing, but this is how YAML works.  You can always choose to quote every string to be clear that they are intended to be strings.
