### ISSUE TITLE
Swagger editor shows undefined for a circular reference

### ISSUE THREAD

**Issue by plahoti** [swagger-api/swagger-editor#1012] opened 2016-07-19 11:13 UTC
I'm working with the following swagger JSON in which the definition for **Product** has a reference to itself. 

```yaml
swagger: '2.0'
info:
  title: Uber API
  version: "1.0.0"
host: api.uber.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /products:
    get:
      summary: Product Types
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Products
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
      capacity:
        type: string
      parent_product:
        $ref: '#/definitions/Product'
```

The output as displayed by the Swagger editor has been attached. As one can see, the type of the field **parent_product** is **undefined**.

![screen shot 2016-07-19 at 4 42 00 pm](https://cloud.githubusercontent.com/assets/16802795/16947978/c21a2940-4dcf-11e6-83b7-9916ff67006a.png)

Please update accordingly. Thanks in advance.

**Comment by webron** [comment] 2016-07-19 17:05
Duplicate of #1005.

**Closed by webron** 2016-07-19 17:05 UTC

**Comment by saharj** [comment] 2016-08-17 05:02
Follow this issue here: https://github.com/whitlockjc/json-refs/issues/91
