### ISSUE TITLE
Resolver error : Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by KevinMitchell** [swagger-api/swagger-editor#2187] opened 2020-06-28 06:59 UTC
Hi,

I'm using the online version of the editor, https://editor.swagger.io/.

I type in the following example (a very simplified version of my real specification).

```
openapi: "3.0.2"

info:
  title: "Test"
  version: "3.3.0"

paths:
  /foo:
    get:
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/a'

components:
  schemas:
    d:
      type: object
   
    b:
      type: object
      properties:
        p:
          allOf:
          - $ref: '#/components/schemas/c'

    a:
      type: object
      properties:
        p:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/b'

    c:
      type: object
      properties:
        p:
          allOf:
          - $ref: '#/components/schemas/d'
```
The result looks fine in the right-hand panel.  However, if I now expand the definition for schema `a` I get a lot of 
```
Resolver error
Cannot read property '0' of undefined
```
errors reported at the top of the page.  I can't see anything wrong with the specifications, and I assume even if there was it shouldn't fail in this way.

Kevin

**Comment by hkosova** [comment] 2020-06-29 06:53
Duplicate of https://github.com/swagger-api/swagger-ui/issues/5820.

See https://github.com/swagger-api/swagger-ui/issues/5820#issuecomment-615540859 for a workaround.

**Closed by hkosova** 2020-06-29 06:53 UTC
