### ISSUE TITLE
Autocompletion of $ref values does not work properly

### ISSUE THREAD

**Issue by Tobias4872** [swagger-api/swagger-editor#1117] opened 2016-11-17 08:44 UTC
**Swagger File**

```yaml
See code snippets below.
```

* Version: 2.10.3
* Browser/OS: 54.0.2840.71 (64-bit) on OSX El Capitan 10.11.6

**Issue**

I admit that this is rather a small problem, but it starts being annoying, so I thought about opening this ticket. The problem is that if I start adding a value for a $ref entity, the autocompletion properly suggests e.g. the available definitions, but if I select one of the definitions the characters I have already typed are not taken into account and the definition reference is just added behind it which requires me to remove the duplicate keys.

Example:

If I define a new model and I start typing

```yaml
definitions:
  ReferredModel:
    type: object
    properties:
      id:
        type: integer

  ReferringModel:
    type: object
    properties:
      other_model:
        $ref: "#/def
```

the autocompletion properly suggests "#/definitions/ReferredModel" as a possible value for the reference, but when I hit return on this selection, the resulting yaml looks like this:

```yaml
definitions:
  ReferredModel:
    type: object
    properties:
      id:
        type: integer

  ReferringModel:
    type: object
    properties:
      other_model:
        $ref: "#/"#/definitions/ReferredModel"
```

So, the character sequence "#/ is duplicated and needs to be removed manually.

Let me know if you have any questions.

Tobias.

**Comment by saharj** [comment] 2016-11-17 20:38
Seems like a duplicate of #807. Should we reopen the issue?

**Comment by saharj** [comment] 2016-12-21 19:48
Closing due to no responce

**Closed** 2016-12-21 19:47 UTC
Labels: duplicate
