### ISSUE TITLE
Getting undefined when giving reference to definition in response of path.   

### ISSUE THREAD

**Issue by Rasika3091** [swagger-api/swagger-editor#1005] opened 2016-07-14 10:04 UTC
- Version: Online Swagger Editor
- Browser/OS:  Browser- Chrome,  OS - Windows 10

Hello,
       I am getting am issue from last week. I am creating documentation for my project. I am using Swagger Editor online. I have some definitions which are interrelated. Means one definition has reference of other definition. Then the response of the path has reference of the definition. But when I take a look at it in demo UI which is shown in the editor, the reference shows undefined. I have given one reference code as example . Please take a look at it in the online editor. You can see that under getUserList list in response the user definition is shown as undefined. I guess this issue is because I have references in both definitions. If I remove the userGroup reference from the user definition, I am able to see user in response. This issue wasn't there a week before. Is anything changed ? Am I suppose to make any other changes to make it work. Please look into this issue because it is a major component of my documentation. Let me know if you need anymore details.
                                                     Thankyou.

Yaml code

``` yaml
swagger: '2.0'
info:
  title: REST API
  description: REST API Documentation
  version: '1.0'
host: 'admin.sd.net:81'
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /getUserList:
    get:
      summary: Get User List
      description: Get User List
      parameters:
        - name: currentId
          in: query
          description: >-
            Provide current Id
          required: false
          type: integer
      tags:
        - User
      responses:
        '200':
          description: Retrieval successful
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        default:
          description: Unexpected error
definitions:
  userGroup:
    type: object
    properties:
      id:
        type: integer
      createdBy:
        type: integer
      createdOn:
        type: string
        format: date
      modifiedBy:
        type: integer
      modifiedOn:
        type: string
        format: date
      state:
        type: integer
      name:
        type: string
      description:
        type: string
      users:
        $ref: '#/definitions/user'
      createdByUser:
        type: string
      modifiedByUser:
        type: string
  user:
    type: object
    properties:
      id:
        type: integer
      createdBy:
        type: integer
      createdOn:
        type: string
        format: date
      modifiedBy:
        type: integer
      modifiedOn:
        type: string
        format: date
      state:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      emailAddress:
        type: string
      users:
        $ref: '#/definitions/userGroup'  
```

**Comment by saharj** [comment] 2016-07-15 04:53
This is the result of [this change](https://github.com/whitlockjc/json-refs/issues/69) in JSON Refs.

It used to resolve circular dependencies until a few levels that was working in editor unless you dig in really deep. 

Then it was changed to resolving to empty object which break previous behavior and now it resolves to `{circular: true}` that to our renderer doesn't mean anything.

If we can get back the original behavior (resolving up to `n` levels) or at least have that as an option in JSON Refs, we can't do much.

/cc @whitlockjc

**Comment by Rasika3091** [comment] 2016-07-15 09:05
Ok. Thanks for opening a bug. Will be waiting for your further response.

**Comment by hrimhari** [comment] 2016-07-18 13:13
My understanding of [this change](https://github.com/whitlockjc/json-refs/issues/69) is that the end result is to have the #ref in place, not an empty object. Has it not been released yet?

**Comment by lxjuly** [comment] 2016-07-27 23:18
I also noticed this problem! I think self-reference is a pretty common practice.

**Comment by saharj** [comment] 2016-08-17 05:02
Follow this issue here: https://github.com/whitlockjc/json-refs/issues/91

**Comment by mobbren** [comment] 2016-08-27 23:41
Commenting to add another voice to this; I'm having the same issue.

Note that https://github.com/whitlockjc/json-refs/issues/91 has been closed as a duplicate of https://github.com/whitlockjc/json-refs/issues/74.

Screenshot of my issue: ![undefined bug](http://i.imgur.com/WnGvXR3.png)

**Comment by Robbilie** [comment] 2016-11-02 18:01
just ran over this issue because my API has some nice circular references, this is pretty annoying :/

**Comment by mennan** [comment] 2017-01-16 11:00
I am getting same issue.

![ref1](https://cloud.githubusercontent.com/assets/201279/21980365/b9882c50-dbeb-11e6-99dd-1395e55af25d.PNG)
![1](https://cloud.githubusercontent.com/assets/201279/21980370/bda4c5c8-dbeb-11e6-911e-6d4fbfd611a8.PNG)

**Comment by lxjuly** [comment] 2017-02-07 23:03
Is there no one actually fixing this?

**Comment by cen1** [comment] 2017-03-06 01:14
So.. as of right now in 2017, circular dependencies are broken in swagger-ui with no workaround? This is like the most basic thing that appears in any API.

**Comment by fehguy** [comment] 2017-03-06 02:09
You'll see a fix shortly

**Comment by gordey4doronin** [comment] 2017-03-27 10:51
Any updates on this? @fehguy

**Comment by webron** [comment] 2017-03-27 22:45
Circular references should no longer be an issue in `master`.

**Comment by cen1** [comment] 2017-03-28 07:32
Not quite yet. It works in only one direction. For example:
```
User:
    type: object
    description: Object representing application user.
    properties:
     cards:
        type: array
        items:
          $ref: '#/definitions/Card' 
```
```
Card:
    type: object
    description: Object representing Petrol pay card.
    properties:
      user:
        $ref: '#/definitions/User'
```
When User object is returned, response JSON correctly contins a card object. When Card object is returned, there is no User object in JSON.

**Comment by gordey4doronin** [comment] 2017-03-30 12:49
@webron 
Can you point me out which code fixes it?
I would like to pull it to `2.x` version.

Or it's not possible already?
It looks like you rewrote the whole thing (I saw two commits: `out with the old`, `in with the new`).

**Comment by webron** [comment] 2017-03-30 14:37
@gordey4doronin - It will not be possible to pull it into `2.x`. 

@cen1 - there's definitely an issue with what you shared, and we're looking into it.

**Comment by webron** [comment] 2017-06-09 06:10
This should no longer be an issue with 3.X. However, if the issue persists, please file a new ticket.

**Closed by webron** 2017-06-09 06:10 UTC
Labels: bug, dependency-issue, sway
