### ISSUE TITLE
Examples not shown in formatted view

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#698] opened 2015-10-26 03:16 UTC
_From @KevinMitchell on October 21, 2015 8:33_

Hi, I've just been getting up to speed with Swagger.  In my test I've attached an examples object to one of my methods.  The editor seems to support this.  However, the examples aren't shown in the formatted view.  Is this not supported, or have I just not enabled something that controls this?

Thanks

_Copied from original issue: swagger-api/swagger.io#50_

**Comment by webron** [comment] 2015-10-26 03:16
Are you talking about swagger-ui?

**Comment by webron** [comment] 2015-10-26 03:16
_From @KevinMitchell on October 22, 2015 7:37_

No, I'm talking about the live rendering view to the right of the editor.  It shows a rendered view of most things you add in the editor, but ignores any examples.

**Comment by chrisdudley** [comment] 2015-10-26 08:01
Duplicate of either or possibly both the following? 
https://github.com/swagger-api/swagger-editor/issues/652 (example attribute within schemas)
https://github.com/swagger-api/swagger-editor/issues/674 (response example attribute)

**Closed** 2015-12-23 16:20 UTC
