### ISSUE TITLE
Unable to get property 'map' of undefined or null reference

### ISSUE THREAD

**Issue by Servus7** [swagger-api/swagger-editor#1371] opened 2017-06-20 08:07 UTC
This error occures when clicking any element in Microsoft Edge 40.15063.0.0.

**Comment by webron** [comment] 2017-06-20 18:29
Using which version of swagger-editor? What do you mean by 'clicking any element'?

**Comment by Servus7** [comment] 2017-06-22 13:59
1. I'm using the web version.
2. Every button or dropdown in the toolbar or the sidepanel.

**Comment by webron** [comment] 2017-06-22 17:31
Thanks. I was able to reproduce the issue as well.

**Comment by ponelat** [comment] 2017-06-23 17:31
This is somehow related to swagger-js and in particular Edge's native `fetch`. We're getting undefined from the `res.body` in topbar.jsx, and its causing `this.state.servers.map` to fail.

https://github.com/github/fetch/issues/407#issuecomment-255724541 is a possible workaround.

**Comment by shockey** [comment] 2017-06-23 19:18
Yeah, so this is an Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9370062/

Looks like a fix is on the way as of Monday:

>  Jun 19, 2017: Changed Status from “Fixed” to “Fixed, not yet flighted”

I'm not too keen on adding code to our repository in order to fix a browser-specific bug that will be patched soon.

You can work around this by removing Edge's native `fetch` implementation before loading the Swagger-UI bundle on a page, so our fetch polyfill will take over:

```
  <script>
    if(window.navigator.userAgent.indexOf("Edge") > -1) {
      console.log("Removing native Edge fetch implementation")
      window.fetch = undefined
    }
  </script>
```

@Servus7, I know you're using the web version, so setting up a custom version of Swagger-UI might be asking much of you. If that's the case, please ping me here and I'll set up a one-off deployment of Swagger-UI with the workaround.

**Comment by shockey** [comment] 2017-06-23 19:22
Closing as wont-fix.

Thanks for reporting this, @Servus7!

**Closed by shockey** 2017-06-23 19:22 UTC
Labels: wont-fix

**Comment by 768123** [comment] 2025-05-22 12:07
@webron @shockey @ponelat @Servus7 @vboctor 
@webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor @webron @shockey @ponelat @Servus7 @vboctor
