### ISSUE TITLE
Add a backend for saving API specs

### ISSUE THREAD

**Issue by zuxfer** [swagger-api/swagger-editor#174] opened 2014-09-19 11:01 UTC
Is it possible to have a feature to save the api defintions directly into the YAML file instead of localstorage. It would be much more helpful for a team division for developing APIs.

**Comment by arun-avanathan** [comment] 2015-06-27 17:51
Any update on this ticket?

**Comment by mohsen1** [comment] 2015-06-27 17:55
Swagger Editor can use a backend but it doesn't have a backed nor it is planned yet.

**Comment by arun-avanathan** [comment] 2015-06-27 18:15
Thanks, where can I find information on how to integrate Swagger Editor with GitHub repository for API specs?

**Comment by arun-avanathan** [comment] 2015-06-29 15:10
@mohsen1 How can we use the backend? Thanks

**Comment by arun-avanathan** [comment] 2015-06-29 15:13
@mohsen1 Never mind, found some information under "Backends" section in the Configuration guide.

**Comment by at15** [comment] 2016-01-31 15:50
the issue is quite old, but it's the first one in google result, if you are a newbie like me, take a look at https://github.com/swagger-api/swagger-node  it supports edit local swagger yaml file and mock server, even a real express server is also supported. maybe @mohsen1  you could add [swagger-node](https://github.com/swagger-api/swagger-node) to readme, it's a lot better than `http-server`

**Comment by fehguy** [comment] 2016-02-01 04:54
Hi having a back end is out of scope for this project.  It's developed so you can add one, but it doesn't belong here in this project.

**Closed by fehguy** 2016-02-01 04:54 UTC
Labels: backend, enhancement

**Comment by jhitchcock** [comment] 2016-02-05 13:44
This is a bit disappointing, though I'm assuming its due to SwaggerHub. Incase anyone (I can name at least 10 people) still needs this feature, FWIW I created something similar by iFraming the editor within a management interface, and dynamically assigning the import parameter, and the back end endpoints, and doing all the tying up outside of the editor. Possibly (without looking in great detail) a bit how swagger hub works

**Comment by fehguy** [comment] 2016-02-05 14:14
It's not due to swagger hub, it's a separation of concerns for this product. Same reason why swagger-UI doesn't ship with a server either.

**Comment by zgiber** [comment] 2016-06-02 08:50
I had the same issue, wrote a small backend to solve it, feel free to try:
https://github.com/zgiber/sweb

**Comment by cato1011** [comment] 2017-02-01 12:56
I know this topic is closed and old, but i created a docker which contains a Swagger "IDE". It includes the Swagger Editor with backend, Swagger UI and Swagger API Mock. The Swagger UI always uses the current yaml of the editor. The Swagger API Mock is reachable under port 8000 and stays also always synchronous with current yaml of the editor. Further information: https://hub.docker.com/r/20029119312185181/swagger-ide/

**Comment by bvipparla** [comment] 2017-02-14 13:52
Thank you @cato1011 - can u share the source for this swagger-ide, if possible.

**Comment by cato1011** [comment] 2017-02-22 12:17
@bvipparla sure: https://github.com/cato1011/swagger-ide

**Comment by darran85** [comment] 2018-02-19 17:42
Cat01011, I tried your docker and it seems working fine. But I have a question: where does it store the yml with your changes in the docker Container? Basically I would like to find the yaml, and maybe have a script that can do git commit/push.

**Comment by bwl21** [comment] 2019-05-30 09:44
> this issue is quite old, but it's the first one in google result, if you are a newbie like me, take a look at https://github.com/swagger-api/swagger-node it supports edit local swagger yaml file and mock server, even a real express server is also supported. maybe @mohsen1 you could add [swagger-node](https://github.com/swagger-api/swagger-node) to readme, it's a lot better than `http-server`

it seems that swagger-node is not really maintained. I installed it via npm but the editor there is pretty old. (2.10.15). I am using 

`docker run -d --rm --name swaggereditor -p 81:8080 swaggerapi/swagger-editor` and would be glad if I could mount a volume with my swaggerfile.

**Comment by pedroasad** [comment] 2020-09-07 19:34
What @bwl21 asked can be accomplished by mounting your swaggerfile/directory as a volume and passing a `SWAGGER_FILE` env-var pointing to it. Something like this:
```bash
docker run -v $(pwd)/path/to/openapi.yaml:/spec/openapi.yaml \
           -e SWAGGER_FILE=/spec/openapi.yaml \
           -p 8080:8080 \
           swaggerapi/swagger-editor
```
It works with both `.yaml` and `.json` files, although it is quite unreadable in JSON. It still requires you to **manually download** the changed file, though :(

I tried all of the suggestions above, in terms of Docker images. Some simply don't work, while others are outdated (old version of Swagger, for instance, which is also the case of an alternative that wasn't listed here, https://github.com/huan/swagger-edit). Too bad we haven't seen any progress on that...

Nonetheless, **these alternatives** (some free, some open source) might help anyone still looking for a satisfiable answer (other than running swagger-ui and hand-editing the openapi.yaml file): https://openapi.tools/#text-editors.

**Comment by erikgratz** [comment] 2022-04-26 16:45
To be honest, the ability to pass in a callback fn that recieves the updated swagger text as a string param would be all I need. Can just take that and overwrite my local swagger file how I see fit. I dont need all this cloud integration, virtual volume, swagger hub stuff. I just wanna use swagger-editor-dist and have it edit a file on my server's local filesystem. But cest la vie, there is always a workaround.
