### ISSUE TITLE
"Only a ReactOwner can have refs" error when clicking on any menu item in 3.0.10

### ISSUE THREAD

**Issue by kappa7194** [swagger-api/swagger-editor#1341] opened 2017-05-29 13:05 UTC
Release v3.0.10 raises a "React error #119" error when clicking on any of the top menu bar ("File", "Edit", "Generate server", "Generate client"), the clicked menu item menu opens but then it's impossible to close it and if it's clicked again another kind of error is raised.

The raised error is:
```
Uncaught Error: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (swagger-editor-bundle.js:32897)
    at Object.addComponentAsRefTo (swagger-editor-bundle.js:37799)
    at r (swagger-editor-bundle.js:37799)
    at Object.s.attachRefs (swagger-editor-bundle.js:37799)
    at h.r (swagger-editor-bundle.js:37799)
    at e.notifyAll (swagger-editor-bundle.js:37799)
    at r.close (swagger-editor-bundle.js:49285)
    at r.closeAll (swagger-editor-bundle.js:37799)
    at r.perform (swagger-editor-bundle.js:37799)
    at i.perform (swagger-editor-bundle.js:37799)
```

Which is mapped to React error "Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded": https://facebook.github.io/react/docs/error-decoder.html?invariant=119

The error raised if the item is clicked again is:
```
Uncaught TypeError: Cannot read property 'componentWillEnter' of undefined
    at o.performEnter (http://localhost:8080/swagger-editor-standalone-preset.js:70:17460)
    at Array.forEach (native)
    at t.componentDidUpdate (http://localhost:8080/swagger-editor-standalone-preset.js:70:18982)
    at e.notifyAll (http://localhost:8080/swagger-editor-bundle.js:64:11600)
    at r.close (http://localhost:8080/swagger-editor-bundle.js:80:4000)
    at r.closeAll (http://localhost:8080/swagger-editor-bundle.js:64:15016)
    at r.perform (http://localhost:8080/swagger-editor-bundle.js:64:14505)
    at i.perform (http://localhost:8080/swagger-editor-bundle.js:64:14422)
    at i.perform (http://localhost:8080/swagger-editor-bundle.js:64:10354)
    at Object.A [as flushBatchedUpdates] (http://localhost:8080/swagger-editor-bundle.js:64:10523)
```

This happens with any schema definition, even the default one.

![image](https://cloud.githubusercontent.com/assets/1249988/26551045/fa5b1050-4480-11e7-9f91-b498e37651cb.png)

**Comment by shockey** [comment] 2017-05-31 07:37
Thanks for reporting this!

This is a known issue (duplicate of https://github.com/swagger-api/swagger-editor/issues/1332). We patched this a couple of weeks ago in 3.0.11, please upgrade to that version to get the fix.

I'm closing this, but feel free to reply if you need any help.

**Closed by shockey** 2017-05-31 07:37 UTC
