### ISSUE TITLE
http/https links problem in production at https://editor.swagger.io

### ISSUE THREAD

**Issue by Somebi** [swagger-api/swagger-editor#1485] opened 2017-09-07 13:45 UTC
https://editor.swagger.io have problems with http/https links

Mixed Content: The page at 'https://editor.swagger.io/#!/' was loaded over HTTPS, but requested an insecure resource 'http://generator.swagger.io/api/gen/download/b386bbc4-0388-4e12-a4a3-3b98d0fb59f9'. This request has been blocked; the content must be served over HTTPS.

Uncaught (in promise) TypeError: Failed to fetch

When trying to download generated server code.

"Generate Server" feature.

**Comment by webron** [comment] 2017-09-07 16:25
@shockey any thoughts?

**Comment by shockey** [comment] 2017-09-07 16:27
This is a duplicate of https://github.com/swagger-api/swagger-editor/issues/1474 😃

**Comment by webron** [comment] 2017-09-07 16:56
Then it must be closed! Thanks for the report, @Somebi.

**Closed by webron** 2017-09-07 16:56 UTC
