### ISSUE TITLE
Not displaying circle reference object

### ISSUE THREAD

**Issue by marcodefreitas** [swagger-api/swagger-editor#1859] opened 2018-08-03 17:12 UTC
### Q&A
 - OS: macOS
 - Browser: chrome 68.0.3440.84, safari 11.1.2 (12605.3.8.1)
 - Swagger-Editor version: online
 - Swagger/OpenAPI version: Swagger 2.0

Example Swagger/OpenAPI definition:
```yaml
  Product:
    type: object
    properties:
      Id:
        type: number
      Package:
        type: array
        items:
          $ref: '#/definitions/Package'
  Package:
    type: object
    properties:
      Product:
        $ref: '#/definitions/Product'
      Other:
        $ref: '#/definitions/Other'
```

### Describe the bug you're encountering
I'm trying to use a circle reference on a nested object but it is not displaying the referenced object.

### Expected behavior
Object Package should display a reference for object Product.

### Additional context or thoughts
If I change Product reference to Other it works and displays correctly. I also tried rearranging positions but it does not display either.

**Comment by hkosova** [comment] 2018-08-15 07:06
Thanks for the report! This issue is currently tracked in https://github.com/swagger-api/swagger-ui/issues/3325.

**Comment by shockey** [comment] 2018-08-15 19:32
Closing as a duplicate of swagger-api/swagger-ui#3325.

**Closed by shockey** 2018-08-15 19:32 UTC
