### ISSUE TITLE
New Editor as Docker-Image?

### ISSUE THREAD

**Issue by Skeeve** [swagger-api/swagger-editor#3416] opened 2022-08-31 05:26 UTC
I'm using the editor in a docker container.

Now there is the new button

<img width="184" alt="image" src="https://user-images.githubusercontent.com/725404/187598971-96c9c43f-1ea0-42c5-ba2c-fc8d434f3e1f.png">

which leads to https://editor-next.swagger.io

Is that editor available as a docker image too? I couldn't find it yet. I'd like to use/test it in my daily work.

**Comment by char0n** [comment] 2022-09-30 08:02
Latest build of SwaggerEditor@next image is available as `swaggerapi/swagger-editor:next-v5` tag. More infor here: https://hub.docker.com/layers/swaggerapi/swagger-editor/next-v5/images/sha256-d5eaff7d57c8d94baa7c3559901d19e5e7ee73ba5b2af44b6188bc20d236f06a?context=explore

**Comment by char0n** [comment] 2022-10-13 10:47
Closing this as I assume existence of `swaggerapi/swagger-editor:next-v5` resolves this issue.

**Comment by Skeeve** [comment] 2022-11-09 08:21
When following your link I get:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/725404/200776639-e4efa26f-643b-4cc4-b775-37b2581aa82e.png">

**Comment by char0n** [comment] 2022-11-09 08:26
Hm dockerhub has some issues, the image is here: https://hub.docker.com/r/swaggerapi/swagger-editor/tags?page=1&name=next

**Comment by Skeeve** [comment] 2022-11-09 08:29
Additionally I do not get the editor when running it with docker-compose.

```compose
  openapi: # profile:NONE
    image: swaggerapi/swagger-editor:next-v5
    environment:
      WITH_CREDENTIALS: "true"
    ports:
    - 8888:80
```

Opening port 8888 on my Browser gives a blank screen. Testing with curl gives:

```html
<!doctype html>
<html lang="en">

<head>
    <link rel="preload" href="/static/media/splash-screen/loader.gif" as="image" type="image/gif" />
    <link rel="preload" href="/static/media/splash-screen/logo.svg" as="image" type="image/svg+xml" />
    <link rel="preload" href="/static/media/splash-screen/styles.css" as="style" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="SwaggerEditor" />
    <link rel="icon" href="/favicon-32x32.png" />
    <link rel="apple-touch-icon" href="/favicon-32x32.png" />
    <link rel="stylesheet" href="/static/media/splash-screen/styles.css" />
    <link rel="manifest" href="/manifest.json" />
    <title>SwaggerEditor</title>
    <script>window.MonacoEnvironment = { baseUrl: new URL("/static/js/", document.baseURI || location.href).toString() }</script>
    <script defer="defer" src="/static/js/main.js"></script>
    <link href="/static/css/main.c411d7d9.css" rel="stylesheet">
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="swagger-editor">
        <div class="swagger-editor">
            <div class="swagger-editor__splash-screen">
                <figure class="swagger-editor__splash-screen-figure"><img width="100%"
                        src="/static/media/splash-screen/logo.svg" alt="Swagger Editor" />
                    <figcaption>5.0.0-alpha.33</figcaption><img width="25" height="25"
                        class="swagger-editor__splash-screen-spinner" src="/static/media/splash-screen/loader.gif"
                        alt="Loading..." />
                </figure>
            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by char0n** [comment] 2022-11-09 08:32
Reopning due to https://github.com/swagger-api/swagger-editor/issues/3416#issuecomment-1308388264

**Comment by char0n** [comment] 2022-11-10 16:12
Possibly related to #3292

**Comment by char0n** [comment] 2022-11-10 16:39
#3292 caused incorrect image builds, and that was the cause of what your blank screen @Skeeve.

Now the image under `next-v5` tag is correctly built. To test:

```sh
 $ docker pull swaggerapi/swagger-editor:next-v5
 $ docker run -p 8888:80 swaggerapi/swagger-editor:next-v5
```
and open your browser at `http://localhost:8888/`.

**Closed** 2022-11-10 17:06 UTC
Labels: type: question, docker, swagger-editor@next

**Comment by Skeeve** [comment] 2022-11-11 06:56
Thanks! Issue solved!

**Comment by char0n** [comment] 2022-11-11 09:47
Just a note: when I'm finished with https://github.com/swagger-api/swagger-editor/issues/3653, the image will be also multi platform capable.
