### ISSUE TITLE
Fails to build on my system

### ISSUE THREAD

**Issue by edwinanto2003** [swagger-api/swagger-editor#792] opened 2016-01-25 20:10 UTC
I am trying to build this locally on my machine but I get an error towards the end of the npm build. I am attaching the npm-debug log along

[npm-debug-log.txt](https://github.com/swagger-api/swagger-editor/files/103857/npm-debug-log.txt)

.

**Comment by saharj** [comment] 2016-01-26 04:09
Duplicate of #743

**Closed by saharj** 2016-01-26 04:09 UTC
Labels: bug
