### ISSUE TITLE
V3.1 breaks scheme output

### ISSUE THREAD

**Issue by ricardofiorani** [swagger-api/swagger-editor#1443] opened 2017-07-31 12:48 UTC
The v3.1 released 2 days ago doesn't show anymore the output scheme. Is this intended or is it a bug? 
It's happening live.

**Comment by webron** [comment] 2017-07-31 15:28
Yes, closing as duplicate of https://github.com/swagger-api/swagger-ui/issues/3489.

**Closed by webron** 2017-07-31 15:28 UTC
