### ISSUE TITLE
Describing a json parameter

### ISSUE THREAD

**Issue by algakzru** [swagger-api/swagger-editor#1855] opened 2018-07-30 03:46 UTC
- OS: Windows 7
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)
 - OpenAPI version: 3.0

### OpenAPI definition
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Trackmeeasy API
paths:
  /getLabelUrl.action:
    post:
      parameters:
        - in: query
          name: filter
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  color:
                    type: string
      responses:
        '200':
          description: OK
```

### Bug description
According to [this](https://swagger.io/docs/specification/describing-parameters) and [this](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object-examples) Swagger supports complex parameters, but when I try to describe a json parameter Swagger Editor shows the following issue: "Could not render ParameterRow, see the console."

### To reproduce...

1. Copy yaml
2. Go to 'http://editor.swagger.io'
3. Paste yaml

### Expected behavior
Json object as a parameter.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/10354348/43381502-74b10202-9407-11e8-852f-3c561c0cd431.png)

**Comment by hkosova** [comment] 2018-07-30 07:39
Thanks, this issue is already tracked in https://github.com/swagger-api/swagger-ui/issues/4442.

<br/>

Just to clarify - are you trying to describe a JSON object send in the _query string_, like so (before URL encoding):

```
POST /getLabelUrl.action?filter={"type":"foo","color":"bar"}
```

or do want to send JSON in the _request body_? In the latter case, you need to use [`requestBody`](https://swagger.io/docs/specification/describing-request-body/) instead of `parameters`.

**Comment by shockey** [comment] 2018-07-31 20:18
Thanks for the report, @algakzru - I'm going to close this as a duplicate of #4442 for now.

**Closed by shockey** 2018-07-31 20:18 UTC
