### ISSUE TITLE
Inconsistent changes with saves

### ISSUE THREAD

**Issue by elsapeng** [swagger-api/swagger-editor#575] opened 2015-07-31 22:37 UTC
When you have several lines of bad indentation, and you fix them and the editor shows the file is saved successfully. But when you open the same file in the browser or just reload the page, only 2-3 lines  indented as you fixed, and the spec is still invalid. The same thing also happen, when you change good indentation to bad indentation.

**Comment by mohsen1** [comment] 2015-08-25 23:05
I've seen this error but I can't reproduce it right now. 
Can you come up with exact steps to reproduce this? Please use the latest master.

**Comment by elsapeng** [comment] 2015-08-26 01:06
Hey @mohsen1, 
Tried the new master branch, the bug seemed to be luckily fixed, the indentation displayed as expected. I am not sure but I tried a lot of examples and no problem happened.

**Comment by mohsen1** [comment] 2015-08-26 03:32
Yes, I saw it's not happening in master either. Maybe it's for when backend is enabled?

**Comment by elsapeng** [comment] 2015-08-26 18:02
What do you mean when backend is enabled? I remember last time I also tried the same yaml file (the minimal.yaml), and it had the indentation problem, but now it's gone.....:)

**Comment by mohsen1** [comment] 2015-09-02 23:10
Since I was not able to reproduce it I'm closing this issue. Please comment here if you found exact steps to reproduce.

**Closed** 2015-09-02 23:10 UTC
Labels: help wanted
