### ISSUE TITLE
Editor fails to load Json from Backend and instantly saves garbage through it and damages original file

### ISSUE THREAD

**Issue by Tokeiito** [swagger-api/swagger-editor#1128] opened 2016-12-07 09:27 UTC
**Swagger File**

```json
{"swagger":"2.0","info":{"title":"Uber API","description":"Move your app forward with the Uber API","version":"1.0.0"},"host":"api.uber.com","schemes":["https"],"basePath":"/v1","produces":["application/json"],"paths":{}}
```

* Version: 2.10.3/2.10.4
* Browser/OS: Chrome/Linux

Editor is configured with backend enabled and yaml disabled. Editor successfully sends 2x (why 2x?) GET requests, but instead showing document in editor, error is shown `options.definition must be either an object or a string`. Also PUT request is fired with body content `["object Object"]` which totally wrecks original file as backend saves it over.

**Comment by saharj** [comment] 2016-12-21 19:44
Duplicate of #853

**Closed** 2016-12-21 19:44 UTC
Labels: duplicate
