### ISSUE TITLE
Bug #363 regression

### ISSUE THREAD

**Issue by centromere** [swagger-api/swagger-editor#1042] opened 2016-08-11 07:31 UTC
It seems that bug #363 is back. If you go to the live editor and add fill out the form for `GET /pets/findByTags` you'll see something like the following:

`GET http://petstore.swagger.io/v2/pets/findByTags?tags%5B%5D=asdfswdef&tags%5B%5D=werwer HTTP/1.1`

AFAIK, the square brackets should not be there.

This also happens with `application/x-www-form-urlencoded` form data.

**Comment by saharj** [comment] 2016-08-13 03:55
It seems like this issue is fixed now.

**Comment by centromere** [comment] 2016-08-13 16:26
@saharj When I change the operation in question from GET to POST and set the content type to `application/x-www-form-urlencoded` I get the following result:

![2016-08-13-122245_1920x1080_scrot](https://cloud.githubusercontent.com/assets/543423/17644323/c0805bd8-6150-11e6-9f4f-17469fa1a8ef.png)

The request body reads:
`tags%5B%5D=foo&tags%5B%5D=bar`

Is this the intended behavior?

**Comment by saharj** [comment] 2016-08-13 16:47
@centromere This is what I get on [editor.swagger.io](editor.swagger.io)

<img width="1395" alt="screen shot 2016-08-13 at 9 43 24 am" src="https://cloud.githubusercontent.com/assets/1468463/17644405/8f5af772-613a-11e6-9405-024788d2ab87.png">

Am I missing something?

**Comment by centromere** [comment] 2016-08-13 16:48
Change the parameter from `query` to `formData`.

**Comment by saharj** [comment] 2016-08-15 04:40
I still don't see any problem. Are you running locally?

**Comment by centromere** [comment] 2016-08-15 06:26
No, this is right from http://editor.swagger.io/ If you load `petstore_full.yaml` and change the method for `/pets/findByTags` from `GET` to `POST` and the parameter from `query` to `formData`, you'll see that when you add tags to the list in the `Try this operation` box, the HTTP content body reads:

`tags%5B%5D=foo&tags%5B%5D=bar`

But, according to @webron in #363, "It shouldn't add the brackets for any collectionFormat". Indeed, this is not correct behavior. The variable in question is named `tags`, not `tags[]`.

**Comment by saharj** [comment] 2016-08-15 23:32
@centromere I'm not able to reproduce this issue. Maybe you would like to take a look on [the URL builder test](https://github.com/swagger-api/swagger-editor/blob/master/test/unit/spec/controllers/tryoperation/generateUrl.js) and let us know which part is not working well.

**Comment by webron** [comment] 2016-08-18 21:40
@saharj - the issue exists, at least in the version at editor.swagger.io.

Following @centromere's directions, I've modified the spec to contain:
```yaml
  /pets/findByTags:
    post:
      tags:
        - pet
      summary: Finds Pets by tags
      description: Muliple tags can be provided with comma seperated strings. Use tag1, tag2, tag3 for testing.
      operationId: findPetsByTags
      produces:
        - application/json
        - application/xml
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
        "400":
          description: Invalid tag value
      security:
        - petstore_auth:
          - write_pets
          - read_pets
```

When running `Send Request`, the payload clearly shows that two formData parameters are being sent, but with the name `tags[]` instead of `tags`.

<img width="452" alt="screenshot 2016-08-18 14 40 20" src="https://cloud.githubusercontent.com/assets/241629/17791739/b691c2a6-6551-11e6-8781-3bfb649dca42.png">

**Comment by saharj** [comment] 2016-09-19 04:39
@webron I don't know the swagger specs very well. Can you please tell me what is the problem in this test? https://github.com/swagger-api/swagger-editor/blob/master/test/unit/spec/controllers/tryoperation/generateUrl.js#L340
Should we add or change anything?

**Comment by webron** [comment] 2016-09-19 21:39
@saharj keep in mind that the test you referenced tests `query` parameters and not `formData`, even though the behavior is similar.

Today, the name of the parameter in the url or payload will always be the name of the parameter in the spec. The `collectionFormat` _never_ affects the name. That means, that even if the `collectionFormat`is `multi`, the name of the parameter will stay as defined (that is, no square brackets are added). The only way to add the square brackets is to actually name the parameter with the square brackets (that is, `tags[]` instead of `tags`).

The `collectionFormat` affects how multiple values are sent. `csv` will separate them by `,` and so will all other formats, except for `multi`. `multi` is the only one that instead of adding a separator character, will repeat the parameter name, each time with a different value. This, again, will not change the name of the parameter as it is constructed in the request.

**Comment by webron** [comment] 2017-06-09 06:19
This should no longer be an issue with the new editor.

**Closed by webron** 2017-06-09 06:19 UTC
Labels: bug, try-operation
