### ISSUE TITLE
recursive expansion doesn't seem to work

### ISSUE THREAD

**Issue by iambingoNJU** [swagger-api/swagger-editor#1725] opened 2018-03-27 02:10 UTC
I want to define a tree structure in swagger. Here is the main definitions:
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: xxx
servers:
  - url: http://localhost:80/ddddd

paths:
  /catalog/{catalogId}/advanced-search:
    post:
      summary: Advanced search a catalog.
      parameters:
        - $ref: '#/components/parameters/catalogId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvancedSearchOption'
      responses:
        '200':
          description: OK
        '500':
          description: NOT FOUND

components:
  parameters:
    catalogId:
      name: catalogId
      in: path
      description: catalog ID
      required: true
      schema:
        type: string

  schemas:
    AdvancedFtsQuery:
      type: object
      properties:
        Operator:
          type: string
        LeftOperand:
          $ref: '#/components/schemas/FtsQuery'
        RightOperand:
          $ref: '#/components/schemas/FtsQuery'
    FtsQuery:
      type: object
      properties:
        AdvancedQuery:
          $ref: '#/components/schemas/AdvancedFtsQuery'
    AdvancedSearchOption:
      type: object
      properties:
        Query:
          $ref: '#/components/schemas/FtsQuery'
```

And the screenshot:
![capture](https://user-images.githubusercontent.com/15451671/37902075-d12e9e08-3125-11e8-8b30-a4f729ec1322.PNG)

The result is that when I expand the **LeftOperand** and the **RightOperand**, it's just empty. If it can't expand recursively, it should at least give a type hint.

environment: Windows 10, Chrome  65.0.3325.181, Swagger Editor online.

Could anybody help?

**Comment by hkosova** [comment] 2018-03-27 17:02
This looks related to (or duplicate of) https://github.com/swagger-api/swagger-ui/issues/3325.

**Comment by iambingoNJU** [comment] 2018-03-28 02:06
Thanks! Sorry for my mispost.

**Closed** 2018-04-03 17:17 UTC
