### ISSUE TITLE
Swagger-editor shows 'undefined' instead of actual type in recursive definitions

### ISSUE THREAD

**Issue by b-filip** [swagger-api/swagger-editor#843] opened 2016-03-14 07:04 UTC
Here is a simple example:

```
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TreeNode'
definitions:
  TreeNode:
    properties:
      value:
        type: string
      left:
        $ref: '#/definitions/TreeNode'
      right:
        $ref: '#/definitions/TreeNode'
```

Swagger-editor shows that the type of `left` and `right` is `undefined`.

**Comment by saharj** [comment] 2016-05-03 22:40
Duplicate of #704

**Closed by saharj** 2016-05-03 22:40 UTC
Labels: bug, dependency-issue, sway
