### ISSUE TITLE
collapsing the documentation window then resizing the browser causes the divider to lose its mind

### ISSUE THREAD

**Issue by paulprogrammer** [swagger-api/swagger-editor#770] opened 2016-01-12 00:05 UTC
steps:
1) press the arrow to collapse the right side (docs)
2) resize the browser smaller
3) observe that the docs half again takes 1/2 the screen, but the collapse arrow is no longer there and you cannot collapse it back (or resize it)

**Comment by paulprogrammer** [comment] 2016-01-12 00:07
Dup of 514

**Comment by mohsen1** [comment] 2016-01-12 00:21
Yes, duplicate of #514 and it's a dependency issue. Please follow the links in that issue.

**Closed** 2016-01-12 00:59 UTC
