### ISSUE TITLE
add a file manage system like StackEdit

### ISSUE THREAD

**Issue by iflamed** [swagger-api/swagger-editor#323] opened 2015-02-03 08:32 UTC
Now, I can't create a named file and save it. That's to say, only one api document can be edit at one time.

StackEdit save the document at the localstorage, swagger-editor also can do that.

Wish swagger-editor will be the press for api writer, like the StackEdit for markdown writer.

**Comment by mohsen1** [comment] 2015-04-29 18:06
Duplicate of #174

**Closed by mohsen1** 2015-04-29 18:06 UTC
Labels: enhancement
