### ISSUE TITLE
Swagger Editor with docker run, no generate server

### ISSUE THREAD

**Issue by orientzc** [swagger-api/swagger-editor#1287] opened 2017-04-21 03:31 UTC
i pull the image(swaggerapi/swagger-editor:latest) of docker hub. and docker run -d -p 80:8080 swaggerapi/swagger-editor:latest. and the show:
![image](https://cloud.githubusercontent.com/assets/17718632/25261687/cffa0cda-2685-11e7-8420-2d1fecf0a112.png)
but i cannot see the generate server,generate client in my local Swagger editor. 

is the swagger editor with docker supported generate server, generate client?
or what do i miss? can anyone help me?

thanks.

**Comment by fehguy** [comment] 2017-04-21 03:52
Hi @orientzc you are correct, the editor at https://editor.swagger.io and the latest docker image are the most current version of the editor, and that is missing the generate buttons.  If you need them, please use the previous version, v2.10.5.  Since this a duplicate of #1224, please follow that issue for resolution.

**Closed by fehguy** 2017-04-21 03:52 UTC

**Comment by orientzc** [comment] 2017-04-21 06:13
@fehguy 
Thanks very much.
