### ISSUE TITLE
False validation error: Non-body parameters require a 'type' property.

### ISSUE THREAD

**Issue by Arekusei** [swagger-api/swagger-editor#1524] opened 2017-10-10 13:10 UTC
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | SwaggerHub and online demo
| How did you install Swagger-Editor? |  
| Which broswer & version?            | FF 56
| Which operating system?             | Win10

### Demonstration API definition
```yaml
---
swagger: "2.0"
info:
  title: "Example"
  version: "dev"
  description: ""
host: "example.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /signup:
    post:
      operationId: "signupPOST"
      description: ""
      tags:
      - auth
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "AuthProviderRequest"
        required: true
        schema:
          $ref: "#/definitions/SignupRequest"
      responses:
        201:
          description: "User registered."
          schema:
            $ref: "#/definitions/SignupResponse"
  /auth/{provider}:
    post:
      description: ""
      operationId: "authProviderPOST"
      tags:
      - auth
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: "provider"
          required: true
          type: "string"
        - in: body
          name: "AuthProviderRequest"
          required: true
          schema:
            $ref: "#/definitions/AuthProviderRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthCredentials"
  /auth/website/{provider}:
    post:
      description: ""
      operationId: "authWebsiteProviderPOST"
      tags:
      - auth
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "provider"
        required: true
        type: "string"
        enum:
          - facebook
          - local
      - in: "body"
        name: "AuthProviderRequest"
        required: true
        description: ""
        schema:
          $ref: "#/definitions/AuthProviderRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthCredentials"
definitions:
  AuthProviderRequest:
    type: "object"
    required:
    - "udid"
    - "parameters"
    properties:
      udid:
        type: "string"
      parameters:
        type: "object"
        properties:
          email:
            type: "string"
          password:
            type: "string"
          authToken:
            type: "string"
  AuthCredentials:
    type: "object"
    properties:
      token:
        type: "string"
  SignupRequest:
    type: "object"
    required:
    - "email"
    - "password"
    properties:
      email:
        type: "string"
      password:
        type: "string"
      udid:
        type: "string"
      termsAccepted:
        type: "boolean"
        default: false
  SignupResponse:
    type: "object"
    properties:
      userId:
        type: "number"
      email:
        type: "string"
      subscriptionStatus:
        type: "number"
```

### Expected Behavior
I think it should be valid.

### Current Behavior
It is regression.
![default](https://user-images.githubusercontent.com/6394535/31387996-3c60aeb6-add5-11e7-8792-2d77b23f2db1.png)

**Comment by Arekusei** [comment] 2017-10-10 13:15
https://editor.swagger.io - shows errors
https://editor2.swagger.io - everything is fine

**Comment by webron** [comment] 2017-10-10 14:26
This is due to #1343 - closing as duplicate.

**Closed by webron** 2017-10-10 14:26 UTC

**Comment by Arekusei** [comment] 2017-10-11 07:39
@webron I tried to investigate a little more and what I find.
These errors connected with error in the definition:
```
  AuthProviderRequest:
    type: "object"
    required:
    - "udid"
    - "parameters"
    properties:
      udid:
        type: "string"
      parameters:
        type: "object"
        properties: # <--- the validator says it's an error
          email:
            type: "string"
          password:
            type: "string"
          authToken:
            type: "string"
```
I think, it isn't connected with 1343, but maybe I am wrong.
If I replace it on this:
```yaml
  AuthProviderRequest:
    type: "object"
    required:
    - "udid"
    - "parameters"
    properties:
      udid:
        type: "string"
      parameters:
        type: "object"
        # properties:
        #   email:
        #     type: "string"
        #   password:
        #     type: "string"
        #   authToken:
        #     type: "string"
```
There are no errors.

Correct me if I'm wrong.

**Comment by webron** [comment] 2017-10-11 09:52
`parameters` is a reserved word of a sort as it is used by the spec. The problem is the reserved words are not based on the location which is causing the issue. If you change the name to `parameters1`, the error will go away.

**Comment by Arekusei** [comment] 2017-10-11 12:20
But, as I said, it was valid in the previous versions. 
And at the moment, I can't change name due to compatibility reasons.

**Comment by webron** [comment] 2017-10-11 14:13
I understand that, and it's a bug, and that bug is covered by the referenced ticket above.

**Comment by Arekusei** [comment] 2017-10-11 15:30
Oh, I see. Thanks.
I just didn't find an example with an inner object definition in the referenced ticket.
