### ISSUE TITLE
The "description:" field within a definition doesn't support GFM formatting

### ISSUE THREAD

**Issue by halmai** [swagger-api/swagger-editor#1426] opened 2017-07-27 14:10 UTC
I wrote the following in the swagger.yaml file:

```
definitions:
    OK-response:
        type: object
        properties:
            result: 
                type: string
                enum: [OK]
                example: "OK"
        description: "
            {

                \"result\": \"OK\"

            }"
                
```

I expected that the JSON in the description appears in a nicely formatted indented JSON. Unfortunately, the indentation does not work, it is just as deep as the { and } symbols.

**Comment by shockey** [comment] 2017-08-04 20:37
@halmai, this is expected behavior. See the discussion here: https://github.com/swagger-api/swagger-ui/pull/3353#issuecomment-314190476

You should be able to preserve whitespace by wrapping your code in triple backticks, which translates to a `<pre>` element in the resulting HTML.

I'm closing this as wontfix, but feel free to reply if you have any further thoughts!

**Closed by shockey** 2017-08-04 20:37 UTC

**Comment by halmai** [comment] 2017-08-05 16:13
According to the https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md specs the `description` should  be able to store a CommonMark description, which, according to the and the http://spec.commonmark.org/0.28/#code-fence part of the specification, should be able to receive fenced code block. So, I think the following should display a nicely indented JSON in the result HTML. 

````
definitions:
    ERROR-response:            
        type: object
        properties:
            result: 
                type: string
                enum: [ERROR]
            error_code: 
                type: string
                enum: [
                  ERROR__C, 
                  ERROR__B,
                  ]
        description: ```
{
   "result": "ERROR"  
}
```
````

Unfortunately, it does not. It doesn't work either if I embed the whole string into a multiline structure:
````
        description: "
```
{
   "result": "OK"  
}
```
"
````
After these ones, I have no more idea how I should create a multi-line description with a code block.

**Comment by hkosova** [comment] 2017-08-05 16:56
@halmai 1) You have an extra comma after `ERROR__B`. 2) This is YAML, so indentation matters. You need to indent like this:

```
definitions:
  ERROR-response:            
      type: object
      properties:
          result: 
            type: string
            enum: [ERROR]
          error_code: 
            type: string
            enum: [ERROR__C, ERROR__B]
      description: >
        This is a paragraph
        of text.

        And some sample JSON:

         ```
         {
          "result": "ERROR" 
         }
         ```

        And here's a code block indented
        using four spaces instead of ```.

            {
              "result": "ERROR" 
            }
```

**Comment by halmai** [comment] 2017-08-05 17:19
@hkosova Thank you so much. I think this is such a valuable information that it would be nice to include in the https://swagger.io/docs/specification/describing-responses/ page of the specification.

**Comment by webron** [comment] 2017-08-06 19:13
@halmai you're in luck, because @hkosova is responsible for that page :wink:.

FYI - the example definition you provided is likely 2.0 and not 3.0.0. 2.0 doesn't support CommonMark, but it does support GFM which still allows for the ``` construct.

**Comment by halmai** [comment] 2017-08-06 23:43
Thank both of you, guys. :)
