### ISSUE TITLE
Doesn't validate headers/parameters that are behind $refs

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-editor#3078] opened 2022-06-01 10:29 UTC
Steps:
As of 2022-06-01
- With editor.swagger.io
- Load the sample definition
Expected:
- 8 validation errors
Actual:
- Only 4 validation errors are shown
![image](https://user-images.githubusercontent.com/8438485/171383924-ddd90943-c8c4-46b5-8b84-806211749199.png)

The sample has three parameters and three headers, each has one valid, one inline but invalid and one behind a $ref but invalid.
- The valid one show no errors (good).
- The invalid/inline shows errors (good).
- The invalid/$ref shows no errors (bad).

## Notes
- OAS 2.0 supported it optional to have either `type` or `schema` fields, and SwaggerUI seems to render that just fine (ish). But OAS 3.0 made banned `type` and made it `schema` or `content` only.

```yaml
openapi: 3.0.3

info: 
  title: Missing validation rule for schemas in Headers.
  version: 1.0.0
  
paths: 
  /foo:
    get:
      description: ok
      parameters: 
      
      - name: one
        in: query
        description: This is a valid parameter
        schema:
          type: string
          
      - name: two
        in: query
        description: This is validated correctly. Missing a `schema` or `content`.
        type: string
        
      - $ref: '#/components/schemas/xFoo' # This isn't validated
      responses:
        default:
          description: ok
          headers:
            one:
              description: This is what a valid header looks like.
              schema:
                type: string
            two:
              type: string
              description: This is validated correctly. Missing a `schema` or `content`.
            three:
              $ref: '#/components/schemas/xFoo' # This isn't valid, but the validator ignores it.
           
components:
  schemas:
    xFoo:
      type: string
      description: This isn't validated correctly
```

**Comment by char0n** [comment] 2022-06-13 08:24
I went as far as [v4.2.2](https://github.com/swagger-api/swagger-editor/releases/tag/v4.2.2) into history but couldn't reproduce generating 8 errors on provided definition. Investigating further...

**Comment by char0n** [comment] 2022-06-13 08:33
Verified that even release from 28 February 2022 doesn't generate 8 errors. Assuming that this haven't worked for a long time or haven't worked at all.

**Comment by char0n** [comment] 2022-06-13 09:02
`json-schema-validator` plugin works as expected; it doesn't try to `dereference` anything before the validation kicks in: https://ajv.js.org/faq.html#generating-schemas-with-resolved-references-ref

Problem might be in `validate-semantic` plugin.

**Comment by char0n** [comment] 2022-06-13 12:46
Fix released as https://github.com/swagger-api/swagger-editor/releases/tag/v4.2.8

**Closed as completed by char0n** 2022-06-13 12:46 UTC
