### ISSUE TITLE
Required boolean parameters have to be set to true

### ISSUE THREAD

**Issue by gbking** [swagger-api/swagger-editor#1051] opened 2016-08-15 08:22 UTC
Swagger-editor will mistakenly detect a required boolean parameter to not be set when its value is set to "false" and therefore not allow to send the request. This should not be the case since "false" should also be a valid value for a boolean parameter. Just because a boolean parameter is required to send the request doesn't mean that it has to be set to "true".

I am experiencing this issue in version 2.10.3 with Chrome on Windows 10.
I am not attaching a swagger file because this issue is easy to replicate in the Swagger editor.

**Comment by saharj** [comment] 2016-08-15 23:39
Yes this is a bug.

**Comment by saharj** [comment] 2016-08-16 00:01
Looks like a duplicate of #542

**Closed by saharj** 2016-08-16 00:01 UTC
Labels: bug, try-operation
