### ISSUE TITLE
Consider moving `react` to `peerDependencies ` in package.json

### ISSUE THREAD

**Issue by HQidea** [swagger-api/swagger-editor#1670] opened 2018-02-11 09:29 UTC
If we're still using `react` lower than 15.6.2, then we will occur an error in broswer:

![image](https://user-images.githubusercontent.com/6296240/36071862-6e74bbea-0f50-11e8-8412-380a818c3b24.png)

It seems there are 2 different versions of `react` loaded.

https://github.com/swagger-api/swagger-editor/blob/fca694783d5e06f65e8d850da4e70b5bec289d4b/package.json#L52-L55

change to

```
// package.json

"peerDependencies": {
  "react": ">=15.0.0",
  "react-dom": ">=15.0.0"
}
```

**Comment by shockey** [comment] 2018-03-07 02:55
Duplicate of https://github.com/swagger-api/swagger-ui/issues/3934; closing

**Closed by shockey** 2018-03-07 02:55 UTC

**Comment by shockey** [comment] 2018-03-07 02:56
(not that you should've known to check there, but the discussion there is applicable to both Swagger-UI and Swagger-Editor!)
