### ISSUE TITLE
GET operation with custom header does not work

### ISSUE THREAD

**Issue by kurtuluso** [swagger-api/swagger-editor#329] opened 2015-02-04 11:54 UTC
I have the following configuration but GET operation does not work with "Try Operation". It has the parameter access_token on header. I've tested the service with another rest client and it is working.
Other operations work but parameter on header has a problem. Response is unknown.

```yaml
/users:
    post:
      description: Authenticates the given facebook access token and returns internal access token. Creates a user with  Facebook information (name, email etc.) related with given Facebook access token if there is no user exists in the system with the Facebook ID. Provided system access token will be used for all REST requests that need authorization. 

      produces:
        - application/json
      parameters:
        - name: fb_access_token
          in: formData
          description: Facebook access token obtained after FB login
          required: true
          type: string
        
      responses:
        '200':
          description: User info with  access token 
          schema:
            $ref: '#/definitions/user_access'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'            

    get:
      description: Validates the give system access token and returns the user info

      produces:
        - application/json
      parameters:
        - name: access_token
          in: header
          description: System access token
          required: true
          type: string

        
      responses:
        '200':
          description: User info with  access token 
          schema:
            $ref: '#/definitions/user_access'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel' 
```

**Comment by iflamed** [comment] 2015-02-04 14:21
I have test in the http://editor.swagger.io via the chrome dev tool, the parameter show in the preview mode but  not  send to the server.

**Comment by ilerian** [comment] 2015-02-04 14:26
that's right. It is correctly displayed on preview but unable to send to server.

**Comment by iflamed** [comment] 2015-02-04 14:29
the api_key mode will add the header to the request.

**Comment by ilerian** [comment] 2015-02-04 14:34
I have not tested but at this time the documentation is corrupted.
The user can not undertand to send access_token in header and required/string etc.

**Comment by iflamed** [comment] 2015-02-04 14:42
it will be fixed

**Comment by kurtuluso** [comment] 2015-02-04 14:45
thank you.
For your time and voluntariness

**Comment by iflamed** [comment] 2015-02-04 15:56
@kurtuluso it's not a bug. When you send the request, it only make a OPTIONS request to server. The get request is not be sent because of the CORS strategy。More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by mohsen1** [comment] 2015-02-04 17:51
This is probably because of XHR CORS limitations. You can fix it by adding your header to `Access-Control-Allow-Headers` in your server. 
If you don't want to change your server, you can host the editor on the same domain or open the editor in Chrome with `--disable-web-security` flag

**Comment by kurtuluso** [comment] 2015-02-06 16:07
Hi,
I've found the reason:
If I want to send "custom" header,
Angularjs sends asks the server if it supports this header.
So that, It sends OPTIONS http call to requested address with "Allow-Control-Request-Headers". The server should response with "Access-Control-Allow-Headers"  header and with correct "Access-Control-Allow-Origin" header.

Angularjs then sends the call with custom header if and only if it gets valid result (200 OK) from OPTIONS call.

I've implemented the CORS filter with  Access-Control-Allow-Headers and it worked!

**Comment by iflamed** [comment] 2015-02-06 17:40
@kurtuluso  It's a brower strategy. How did you implement the CORS fiter, Could you post pr or paste your code to us?

**Comment by kurtuluso** [comment] 2015-02-06 18:46
It may be browser strategy but this tool should directly process the request. Chrome extension "Advanced REST client" can directly sent the request without OPTIONS. I think somehow you can handle this with advanced coding.

The CORS info is below for java/jersey. You should also register "ResponseCORSFilter" on the application or web.xml


package org.quran.qurantools.core;
import org.glassfish.jersey.server.ContainerRequest;
import org.glassfish.jersey.server.ContainerResponse;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerResponseContext;
import javax.ws.rs.container.ContainerResponseFilter;
import javax.ws.rs.core.Response;
import java.io.IOException;
/**
 * Created by kurtulus on 05/02/15.
 */
public class ResponseCORSFilter implements ContainerResponseFilter {
    @Override
    public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext contResp) throws IOException {
        contResp.getHeaders().add("Access-Control-Allow-Origin", "*");
        contResp.getHeaders().add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
        contResp.getHeaders().add("Access-Control-Allow-Headers", "access_token");
    }
}

**Closed** 2015-02-12 16:35 UTC
Labels: question
