### ISSUE TITLE
Installing swagger editor locally

### ISSUE THREAD

**Issue by Rasika3091** [swagger-api/swagger-editor#1020] opened 2016-07-25 10:19 UTC
- Version: Swagger 2.10.3
- Browser/OS: Chrome Version 51.0.2704.103 m (64-bit) , Windows 10

Hello,

```
 I need some help. I am not able to install swagger editor locally. 
```

This is the link I am referring,
       https://github.com/swagger-api/swagger-editor

I have downloaded swagger v2.10.3 
Then I am running it locally. Followed these steps.

npm install -g http-server
wget https://github.com/swagger-api/swagger-editor/releases/download/v2.10.3/swagger-editor.zip
unzip swagger-editor.zip
http-server swagger-editor

At the end when I start the server and run the given url in Chrome. Its not working.
Giving me issue ,

```
[Mon Jul 25 2016 15:22:06 GMT-0700 (Pacific Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[Mon Jul 25 2016 15:22:06 GMT-0700 (Pacific Daylight Time)] "GET /" Error (404): "Not found"
[Mon Jul 25 2016 15:22:07 GMT-0700 (Pacific Daylight Time)] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[Mon Jul 25 2016 15:22:07 GMT-0700 (Pacific Daylight Time)] "GET /favicon.ico" Error (404): "Not found"
[Mon Jul 25 2016 15:22:53 GMT-0700 (Pacific Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
```

Can you tell me what am I missing ?

Thankyou.

**Comment by saharj** [comment] 2016-07-25 11:40
I'm not sure what the problem is. Try `http-server -p` with some other port. Maybe this will fix your problem.

**Comment by seecomedia** [comment] 2016-07-25 11:52
Hi.
Could be an option to use -o so that it will open browser right after starting pointing to correct URL. Ref nam http-server page:

-o Open browser window after starting the server

**Comment by Rasika3091** [comment] 2016-07-26 05:04
Hello, I tried giving port number with -p but still it did not work. 
I even tried -o , but its opening the swagger folder and not the browser.

**Comment by annatara1** [comment] 2016-07-26 19:15
has this been solved? I am facing a similar issue

**Comment by jokefaker** [comment] 2016-08-22 07:50
Same issue too

**Comment by HardySoftware** [comment] 2016-11-10 15:45
Same issue here. I can see the browser hits the web server, but server responded 404 code.

**Comment by poolieweb** [comment] 2016-11-22 11:35
Same here

**Comment by rhycce** [comment] 2016-12-21 23:22
Hi, has this issue been resolved. I'm facing a similar issue. The only twist in mine was after the installation, I got the editor running once through a browser. After a few modifications on the browser editor, the swagger-editor shutdown unexpectedly. I restarted using the `http-server swagger-editor` and I get the
`Available on:   http://ipaddress:port` response. But trying to access the editor via browser results in a 404 not found error.

**Comment by akoskm** [comment] 2017-01-19 15:40
I followed this tutorial: https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger.

While starting swagger from the local node_modules folder worked:

```
./node_modules/swagger project start example
```

I'm receiving 404 from the editor

```
./node_modules/swagger project edit example
```

Can someone confirm that swagger-editor work only if it's installed globally?

**Comment by akoskm** [comment] 2017-01-19 16:52
The exact same order of commands works when swagger is installed globally.

**Comment by narayanjr** [comment] 2017-01-22 00:21
I just had the same issue and I realized it is because I was running the http-server command from the wrong location.  If you do http-server swagger-editor from within the extracted zip contents, it produces those errors when trying to get to the page.

Make sure you are not in the "swagger-editor" directory when running the command.  You need to be one level higher.

**Comment by FrancescoRizzi** [comment] 2017-03-03 12:54
Indeed, this may be worth of noting on the [docs](http://swagger.io/docs/#setup-with-http-server-module-from-github-5) (incidentally, those still refer to v.2.10.4) and [readme](https://github.com/swagger-api/swagger-editor/blob/master/README.md)

**Comment by webron** [comment] 2017-06-09 06:11
Closing as we don't actively maintain 2.x. If anyone wants to submit a PR against the 2.x docs, we'll look into merging it.

**Closed by webron** 2017-06-09 06:11 UTC
Labels: question

**Comment by pykvyas** [comment] 2019-06-12 21:33
I see the below in the cmd prompt when I tried to access the addresses mentioned nothing is happening. the web page is just blank.

And I would like to know the prerequisites 

![image](https://user-images.githubusercontent.com/4861689/59387825-fe825380-8d1e-11e9-90ec-d48c3e690c6b.png)

ANy help is highly appreciated.
