### ISSUE TITLE
Example Value is not updated after model is changed

### ISSUE THREAD

**Issue by lbcsy** [swagger-api/swagger-editor#1806] opened 2018-06-28 23:09 UTC
### To reproduce...

1. Go to Live Demo
2. Click on pet POST on the viewer on the right side
3. Scroll down to its Example Value, the first property is "id"
4. Go back to the code on the left side, scroll down to schema definition for Pet, change line 657 from "id" to "id1", the viewer is refreshed automatically, but the Example Value still show "id" instead of "id1"
5. Refresh whole page by click browser's refresh button, the "id" then changed to "id1"

### Expected behavior
It is expected to see the change in Viewer after it refreshed without refresh the whole page.

**Comment by shockey** [comment] 2018-07-09 20:32
@lbcsy, it looks like this is working in the latest version:

![](http://g.recordit.co/ToN9TabvlK.gif)

Closing - let me know if I reproduced this incorrectly!

**Closed by shockey** 2018-07-09 20:32 UTC
