### ISSUE TITLE
Required number parameter can't be set to zero

### ISSUE THREAD

**Issue by smartpunter** [swagger-api/swagger-editor#717] opened 2015-11-17 18:46 UTC
Parameter
  type: "number"
  required: true
  minimum: 0
  maximum: 2
When setting this parameter to 0 editor (Version 2.9.8) says "Property must be set."

Expected behavior - allow to send 0 as required number parameter.

**Comment by webron** [comment] 2015-12-23 20:51
This is a duplicate of #472 (though this is more generic).

**Closed by webron** 2015-12-23 20:51 UTC
