### ISSUE TITLE
Always get validation error when pasting a Swagger json -  "options.definition is required"

### ISSUE THREAD

**Issue by weching** [swagger-api/swagger-editor#668] opened 2015-09-24 01:04 UTC
There's some issue for validation when pasting a swagger json no matter the swagger file is invalid or not, I always get this error:

Error
 Object
message:  "options.definition is required"
code:  "ERROR_THROWN_BY_SWAY_CODE:undefined"

**Comment by mohsen1** [comment] 2015-09-24 02:10
Are you using the latest version? I can't reproduce this.

**Comment by bmulyawan** [comment] 2015-09-27 10:32
i got this as well.. on http://editor.swagger.io/ even if i export the example to json and paste it back

**Comment by mohsen1** [comment] 2015-09-27 16:47
You mean File -> Import JSON option. Ok got it.

**Comment by eschizoid** [comment] 2015-10-06 22:54
Same here

Attached the json document

{code:javascript}
{
  "apiVersion": "1.0",
  "apis": [
    {
      "description": "Admin Controller",
      "path": "/default/admin-controller",
      "position": 0
    },
    {
      "description": "Atg Private Api Controller",
      "path": "/default/atg-private-api-controller",
      "position": 0
    },
    {
      "description": "Atg Public Api Controller",
      "path": "/default/atg-public-api-controller",
      "position": 0
    },
    {
      "description": "Logout Controller",
      "path": "/default/logout-controller",
      "position": 0
    },
    {
      "description": "Mobile Controller",
      "path": "/default/mobile-controller",
      "position": 0
    },
    {
      "description": "Profile Controller",
      "path": "/default/profile-controller",
      "position": 0
    },
    {
      "description": "Synergy Private Api Controller",
      "path": "/default/synergy-private-api-controller",
      "position": 0
    },
    {
      "description": "Synergy Public Api Controller",
      "path": "/default/synergy-public-api-controller",
      "position": 0
    }
  ],
  "authorizations": {
    "oauth2": {
      "grantTypes": {
        "implicit": {
          "loginEndpoint": {
            "url": "https://www.stopandshop.com/auth/login.jsp"
          },
          "tokenName": "access_token",
          "type": "implicit"
        }
      },
      "scopes": [
        {
          "description": "Used to proxy to Synergy and ATG",
          "scope": "profile"
        }
      ],
      "type": "oauth2"
    }
  },
  "info": {
    "contact": "XXXX",
    "description": XXXX",
    "license": "XXXX",
    "licenseUrl": "XXXX",
    "termsOfServiceUrl": "XXXX",
    "title": "OAuth REST API"
  },
  "swaggerVersion": "1.2"
}
{code}

Using spring swagger latest version:

{code:xml}
<dependency>
	<groupId>com.mangofactory</groupId>
	<artifactId>swagger-springmvc</artifactId>
	<version>1.0.2</version>
</dependency>
{code}

**Comment by webron** [comment] 2015-10-06 22:56
@eschizoid - swagger-editor supports Swagger 2.0 only. The output you shared is Swagger 1.2 and it looks like you're using a really old version of swagger-springmvc. Please consider upgrading to the latest version of the product, now called [springfox](https://github.com/springfox/springfox).

**Comment by eschizoid** [comment] 2015-10-06 23:08
@webron Doing right now ;)

**Comment by eschizoid** [comment] 2015-10-07 04:00
@webron seems that swagger editor is working now, however still getting some errors when using `java.security.Principal`

**Comment by TheToolbox** [comment] 2015-10-13 18:17
This issue still persists. When running with backend on and YAML mode off, JSON files are improperly read, but end up being written (via PUT) correctly.

**Comment by shmeeps** [comment] 2015-10-14 19:53
Appears to be reproduceable on editor.swagger.io.

1. File -> New
2. File -> Download JSON
3. File -> Paste JSON (use the contents of the downloaded file)

```
    message: "options.definition is required"
    code: "ERROR_THROWN_BY_SWAY_CODE:undefined"
```

Even adding a small definitions section appears to continue giving the error

**Comment by sibblegp** [comment] 2015-10-14 20:32
I always get this error as well even with perfectly valid Swagger 2.0 code.

**Comment by itainteasy** [comment] 2015-10-18 00:32
OK so here is how to reproduce the error when you are trying to bring your **json** into the _**[swagger online editor](http://editor.swagger.io/)**_: 

1. While you're at http://editor.swagger.io/ we goto `File -> Paste JSON...`
2. Paste the following JSON (_it was generated by using `File -> Open Example...` and choosing minimal):  `
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.0",
    "title": "Simple API"
  },
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
`

3. You will get the error:
>message: "options.definition is required"
>code: "ERROR_THROWN_BY_SWAY_CODE:undefined"

4. Now, let's add a root property called "definition" and encapsulate everything (above) to become it's property: `{
  "definition": {
    "swagger": "2.0",
    "info": {
      "version": "0.0.0",
      "title": "Simple API"
    },
    "paths": {
      "/": {
        "get": {
          "responses": {
            "200": {
              "description": "OK"
            }
          }
        }
      }
    }
  }
}`
You will now get "✔ Valid Swagger".. click Import.

5. Now the editor is displaying an error:
>Unknown Error
>Unable to identify the Swagger version or the Swagger version is unsupported
This is because we had to add the definition property to the root and move everything into it to pass the paste & import step.
Simply delete the first line of which has `definition:` and viola.


**__Your final YAML looks like:__**
```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        '200':
          description: OK
```

If you use the editor to `File -> Download JSON` you will have to do this again to get things back into it. Per the [Swagger 2.0 Spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema) the field/property "definition" is not allowed anywhere.

I recommend using https://restunited.com/ against your exports from https://www.getpostman.com/ to handle proper conversions for now at least it's the simplest/quickest way to convert your postman collections into swagger &/or YAML.

I'd put my money on this being strictly related to the editor itself expecting this field.. I'll check out the code when I get some more free time.

Hope this helps!

**Comment by wilsonge** [comment] 2016-01-18 15:50
I can reproduce the error and can confirm the "temp" fix by @itainteasy fixes the issue as a workaround

**Comment by saharj** [comment] 2016-02-07 19:12
This is a duplicate of #805.

**Closed by saharj** 2016-02-07 19:12 UTC
Labels: bug
