### ISSUE TITLE
Running 'npm run build' before 'npm start'

### ISSUE THREAD

**Issue by stcrestrada** [swagger-api/swagger-editor#953] opened 2016-05-28 22:06 UTC
I'm using the latest swagger-editor@2.10.1. I git cloned the repository locally, in lieu of forking it over then cloning, separate issue with Github. 

I had an issue with the command 'npm start': the browser opened; however, the static files weren't loading and a blank page was displayed. After inspecting the console on google chrome the problem was that the dist folder was not being created, which is where the static files are stored. After looking through the code, I noticed the script 'npm run build' in package.json, so the fix was running 'npm run build', then 'npm start' and the swagger-editor loaded successfully. 

I am still getting an error in the chrome console "http://127.0.0.1:8080/dist/undefined", but the page appears to be working. Not sure if anyone else had this problem, but I found what appears to be a nice work around --> 'npm run build' --> 'npm start'

Thanks, 
Stephen

**Comment by Vasiok** [comment] 2016-05-31 10:46
@stcrestrada 
Thanks dude that worked for me as well

**Comment by nodo** [comment] 2016-05-31 12:31
Thanks @stcrestrada.

Related problem: is there a way to run the `swagger-editor` locally without building it first?

**Comment by saharj** [comment] 2016-05-31 21:58
@nodo If you git clone the repository, you have to build it first.

**Comment by saharj** [comment] 2016-05-31 22:02
Duplicate of #890

**Closed by saharj** 2016-05-31 22:02 UTC
