### ISSUE TITLE
Cannot edit swagger on new file on Chrome 

### ISSUE THREAD

**Issue by Steph0** [swagger-api/swagger-editor#570] opened 2015-07-24 09:26 UTC
Windows 7 entreprise
Chrome : Version 43.0.2357.134 m
url : http://editor.swagger.io/#/

Issue : 
- When I create a new file
- I just try to type something, nothing happen (cannot type, delete or do anything else on text)
- This issue does not happen on Firefox latest version

Error in console (note: code is compressed but not uglifyed) : 
```
Uncaught TypeError: c.getMode(...).transformAction is not a function
remove @ 98f65023.vendor.js:18
b.commands.exec @ 98f65023.vendor.js:17
(anonymous function) @ 98f65023.vendor.js:16
d._emit.d._dispatchEvent @ 98f65023.vendor.js:12
exec @ 98f65023.vendor.js:16
$callKeyboardHandlers @ 98f65023.vendor.js:13
onCommandKey @ 98f65023.vendor.js:13
onCommandKey @ 98f65023.vendor.js:17
d @ 98f65023.vendor.js:12
(anonymous function) @ 98f65023.vendor.js:12
```

**Comment by mohsen1** [comment] 2015-07-25 17:47
Duplicate of #565

**Comment by mohsen1** [comment] 2015-08-25 22:57
Fixed by 82a26a6

**Closed** 2015-08-25 22:57 UTC
Labels: bug, duplicate

**Comment by sram54** [comment] 2017-06-06 16:31
I am unable to edit my Swagger API. I get a message on top right hand corner - Read Only. How do I enable editing?

**Comment by webron** [comment] 2017-06-06 16:47
@sram54 which version of swagger-editor do you use?

**Comment by joanlofe** [comment] 2018-04-16 10:46
Only for reference, for those who find this bug, editor is working again if you set Mode: Yaml in Preferences --> Editor settings
