### ISSUE TITLE
Enum doesn't display properly if missing a description

### ISSUE THREAD

**Issue by ckriley** [swagger-api/swagger-editor#856] opened 2016-04-01 15:44 UTC
The following swagger.json renders the enum properly in the swagger-tools online

``` json
"state": {
          "description": "State details of student",
          "type": "string",
          "enum": [
            "MA",
            " NH",
            " VT",
            " RI",
            " CT",
            " ME"
          ]
        }
```

The following swagger.json does not render the enum properly and allow for drilling down into the Array of String

``` json
"state": {
          "type": "string",
          "enum": [
            "MA",
            " NH",
            " VT",
            " RI",
            " CT",
            " ME"
          ]
        }
```

**Comment by saharj** [comment] 2016-04-05 19:26
I can not reproduce this issue. Can you give us the full swagger code?

**Comment by ckriley** [comment] 2016-04-05 19:36
Here is a full sample. The state is enum and doesn't render as such. If you add description it does.

{
  "swagger": "2.0",
  "info": {
    "title": "Student",
    "version": "1.0.0"
  },
  "paths": {
    "/student": {
      "post": {
        "summary": "creating a student",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "student",
            "schema": {
              "$ref": "#/definitions/student"
            },
            "in": "body"
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      },
      "get": {
        "summary": "gets a student",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "type": "number",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/student"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "address": {
      "title": "address",
      "description": "address details for student",
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string",
          "enum": [
            "MA",
            " CT",
            " RI",
            " VT",
            " ME",
            " NH"
          ]
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "student": {
      "title": "student",
      "required": [
        "firstname",
        "lastname"
      ],
      "type": "object",
      "properties": {
        "firstname": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/address"
        }
      }
    }
  }
}

**Comment by copynpaste** [comment] 2017-02-15 10:49
Seems this can be closed since the dependency to json-schema-view-js is bumped to 1.0.0 and will be in the next release?

**Comment by webron** [comment] 2017-06-09 03:31
This should no longer be an issue in 3.X.

**Closed by webron** 2017-06-09 03:31 UTC
Labels: bug, dependency-issue
