### ISSUE TITLE
Documentation for swagger-editor 3?

### ISSUE THREAD

**Issue by moon0326** [swagger-api/swagger-editor#1345] opened 2017-05-30 23:49 UTC
Hi,

I'm trying to use swagger-editor with a backend to save changes back to file to avoid copy/paste or downloading the content as json or yaml.

I could do it with swagger-editor 2 by looking at https://github.com/swagger-api/swagger-node/blob/master/lib/commands/project/swagger_editor.js

Is there a way to do the same in swagger-editor 3?

**Comment by webron** [comment] 2017-05-31 01:02
This is a duplicate of #1241 - but currently we have no immediate plans on implementing it.

**Closed by webron** 2017-05-31 01:02 UTC

**Comment by moon0326** [comment] 2017-05-31 02:19
Thank you Ron.
