### ISSUE TITLE
SwaggerEditor@next: Bad UX when opening detail of opblock

### ISSUE THREAD

**Issue by romanblanco** [swagger-api/swagger-editor#3523] opened 2022-09-30 20:37 UTC
### Q&A (please complete the following information)
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 105.0.1 (64-bit)
 - Method of installation: -
 - Swagger-Editor version: next
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

https://raw.githubusercontent.com/RedHatInsights/compliance-backend/fab750a1268e1589b256892dc8086eb4db954413/swagger/v1/openapi.json

### Describe the bug you're encountering

The arrow next to `opblock-summary-description` moves away from it's position on hover.

![image](https://user-images.githubusercontent.com/1187051/193351586-f95f1585-f3f7-43da-93a3-b1d91e4bf26e.png)

![screenshot](https://user-images.githubusercontent.com/1187051/193352189-dc8c5903-e953-404c-8341-24be1597f69d.png)

### Expected behavior
The arrow's position stays

**Comment by char0n** [comment] 2022-10-03 06:48
Hi @romanblanco,

SwaggerEditor just uses SwaggerUI which displays the operations. Would be able to submit this issue under [SwaggerUI repository](https://github.com/swagger-api/swagger-ui/) and provide a lint the SwaggerUI issue here? 

Thanks!

**Comment by BasilaryGroup** [comment] 2023-03-13 13:25
Please see [Inconvenient "copy to clipboard" button behaviour #8153](https://github.com/swagger-api/swagger-ui/issues/8153).

**Comment by char0n** [comment] 2023-03-25 09:04
Closing this as duplicate of https://github.com/swagger-api/swagger-ui/issues/8153 and is being addressed in https://github.com/swagger-api/swagger-ui/pull/8465

**Closed by char0n** 2023-03-25 09:04 UTC
