### ISSUE TITLE
Docker Image of 2.10.5 still serving 2.10.4

### ISSUE THREAD

**Issue by jehof** [swagger-api/swagger-editor#1202] opened 2017-03-02 09:21 UTC
We use the latest Docker Image v2.10.5 (https://hub.docker.com/r/swaggerapi/swagger-editor/) of swagger editor but it is still serving v2.10.4.

Previously we have Docker Image v2.10.4 installed, but we have updated to the latest image using portainer.io

At least Menu->About Swagger Editor->Version 2.10.4 is telling that us.

So, is the version not reflected correctly in the UI or is image v2.10.5 still on v2.10.4. Does this relate to https://github.com/swagger-api/swagger-editor/issues/1198 and https://github.com/swagger-api/swagger-editor/issues/1191.

**Comment by saharj** [comment] 2017-03-04 00:59
The issue is fixed now.

**Closed** 2017-03-09 23:47 UTC
