### ISSUE TITLE
Can't figure out this

### ISSUE THREAD

**Issue by HEDIDIN** [swagger-api/swagger-editor#720] opened 2015-11-22 20:02 UTC
I cannot figure out why I am getting this error. I have the same input parameter throughout. 

![swaggererror](https://cloud.githubusercontent.com/assets/6843907/11325949/121d9d80-9121-11e5-8d80-f7252efcba74.png)

             Swagger Error
```
Not a valid parameter definition
Jump to line 269
Details
 Object
code:  "ONE_OF_MISSING"
message:  "Not a valid parameter definition"
 path: Array [5]
 inner: Array [2]
 0: Object
 1: Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY"
message:  "Missing required property: $ref"
 path: Array [5]
0:  "paths"
1:  "/{rid-db}/colls"
2:  "post"
3:  "parameters"
4:  "4"
level: 900
type:  "Swagger Error"
description:  "Not a valid parameter definition"
lineNumber: 269

  -name: x-ms-version
          description: The version 2015-08-06 of DocumentDB REST service.
          type: string
          in: header
          required: true
          name: x-ms-date
          in: header
          required: true
          description: 'The date of the request The date is expressed in Coordinated Universal Time format. 08 Apr 2015 03:52:31 GMT'
          type: string
        - name: Request
          description: This is a user settable property. It is the unique name that identifies the collection
          in: body
          type: string
          required: true
          schema:
            $ref: '#/definitions/CustomBodyCollection'
```

**Comment by fehguy** [comment] 2015-11-23 02:36
Can you please share more of your spec?  Not enough here to help

**Comment by HEDIDIN** [comment] 2015-11-23 15:48
I have attached the complete spec
[HEDIDIN-DocumentDBConnector-1.0.4-swagger.json.txt](https://github.com/swagger-api/swagger-editor/files/41734/HEDIDIN-DocumentDBConnector-1.0.4-swagger.json.txt)

**Comment by webron** [comment] 2015-11-24 00:30
@HEDIDIN did you mean to close the issue? is it resolved for you?

**Comment by HEDIDIN** [comment] 2015-11-24 02:46
No. You asked for more of my spec. So I attached the complete

**Comment by webron** [comment] 2015-11-24 02:56
Your `Request` body parameter has the property `type` which is invalid for body parameters. Try removing it and see if it helps.

**Comment by HEDIDIN** [comment] 2015-11-24 03:07
Ron,

 

I removed the type for all body parameters. Now I get

 


 Swagger Error


Not a valid parameter definition

Jump to line 111

Details

 Object

code: "ONE_OF_MISSING"

message: "Not a valid parameter definition"

 path: Array [5]

 inner: Array [2]

level: 900

type: "Swagger Error"

description: "Not a valid parameter definition"

lineNumber: 111

✖ Swagger Error

Not a valid parameter definition

Jump to line 97

Details

 Object

code: "ONE_OF_MISSING"

message: "Not a valid parameter definition"

 path: Array [5]

 inner: Array [2]

level: 900

type: "Swagger Error"

description: "Not a valid parameter definition"

lineNumber: 97

**Comment by webron** [comment] 2015-11-24 03:08
The problem is that without the exact *YAML* that you're using I can't tell what's in those line numbers. I'd either need the full expanded errors or the current version of your YAML file.

**Comment by HEDIDIN** [comment] 2015-11-24 03:13
I have attached the yaml
[HEDIDIN-DocumentDBConnector-1.0.4-swagger.yaml.txt](https://github.com/swagger-api/swagger-editor/files/42323/HEDIDIN-DocumentDBConnector-1.0.4-swagger.yaml.txt)

**Comment by HEDIDIN** [comment] 2015-11-24 03:15
Swagger Error

Not a valid parameter definition

Jump to line 111

Details

 Object

code: "ONE_OF_MISSING"

message: "Not a valid parameter definition"

 path: Array [5]

0: "paths"

1: "/"

2: "post"

3: "parameters"

4: "3"

 inner: Array [2]

 0: Object

code: "ONE_OF_MISSING"

message: "Data does not match any schemas from 'oneOf'"

 path: Array [5]

 inner: Array [2]

 0: Object

 1: Object

code: "OBJECT_MISSING_REQUIRED_PROPERTY"

message: "Missing required property: type"

 path: Array [0]

 1: Object

code: "OBJECT_MISSING_REQUIRED_PROPERTY"

message: "Missing required property: $ref"

 path: Array [5]

0: "paths"

1: "/"

2: "post"

3: "parameters"

4: "3"

level: 900

type: "Swagger Error"

description: "Not a valid parameter definition"

lineNumber: 111

✖ Swagger Error

Not a valid parameter definition

Jump to line 97

Details

 Object

code: "ONE_OF_MISSING"

message: "Not a valid parameter definition"

 path: Array [5]

0: "paths"

1: "/"

2: "post"

3: "parameters"

4: "0"

 inner: Array [2]

 0: Object

 1: Object

code: "OBJECT_MISSING_REQUIRED_PROPERTY"

message: "Missing required property: $ref"

 path: Array [5]

0: "paths"

1: "/"

2: "post"

3: "parameters"

4: "0"

level: 900

type: "Swagger Error"

description: "Not a valid parameter definition"

lineNumber: 97

**Comment by webron** [comment] 2015-11-24 03:22
In this case you have to issues, both at POST / (the root):
- The `Content-Type` parameter is missing a `type`. As a side note, you should not specify the `Content-Type` header directly. This is why operations have the `consumes` property.
- Your `id` body parameter is missing the `schema` property.

**Comment by HEDIDIN** [comment] 2015-11-24 03:30
Thank you for your help

**Comment by webron** [comment] 2015-11-24 03:30
With pleasure. Any other issues with your current spec?

**Comment by HEDIDIN** [comment] 2015-11-24 03:31
I need to learn to read the help docs: -)

**Comment by webron** [comment] 2015-11-24 03:33
The spec may seem long, but it's actually fairly straight forward. If you have any questions about the structure or the spec, I'd suggest posting those in the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).

Would it be ok if we close this issue for now?

**Comment by HEDIDIN** [comment] 2015-11-24 03:34
Yes. 

 

Thanks again

**Closed** 2015-11-24 03:35 UTC

**Comment by SandeshSarfare** [comment] 2016-05-25 06:13
![image](https://cloud.githubusercontent.com/assets/16500341/15529824/ce023b72-226d-11e6-906a-f4bfe1e1a0cb.png)

**Comment by SandeshSarfare** [comment] 2016-05-25 06:14
I have trying changing format: JSON to string but that too does not work and its the same error

**Comment by HelioGuilherme66** [comment] 2016-05-25 09:29
@SandeshSarfare I think you should ask for help in the google-group, not in Issues (even if Closed).
Anyway, I suspect you are missing at line 6996 a `format: JSON` or other format.

**Comment by SandeshSarfare** [comment] 2016-05-25 09:52
My primary observation was the same but that is not working...anyways thanks for the suggestion. I will ask on Google Group

**Comment by grcreddy** [comment] 2016-07-12 11:39
Hi Webron,

i tried to crate XML Schema for Swagger2.0 getting below error. could you please help me out.
![1](https://cloud.githubusercontent.com/assets/20418763/16765683/1e6abb42-4853-11e6-8af5-2e10aa49c7c7.jpeg)

**Comment by grcreddy** [comment] 2016-07-13 05:28
Hi Webron,

i tried to crate XML Schema for Swagger2.0 getting below error. could you please help me out.

**Comment by grcreddy** [comment] 2016-07-13 05:32
[1.yaml.txt](https://github.com/swagger-api/swagger-editor/files/360762/1.yaml.txt)

**Comment by paraglohiya** [comment] 2016-08-23 23:36
I am facing same issue with Swagger.

**Comment by fehguy** [comment] 2016-08-23 23:52
ok @grcreddy you have a bunch of syntax errors in your document, so no, it cannot validate correctly.  I've attached a cleaned-up doc below.

Please note:
* In YAML, tabs are evil
* You must follow YAML indenting syntax
* Without `:` after a key, you will get an error.

See below, I suggest that if you're going to use the editor, you do your work in there to avoid tabs and other formatting horrors.

```
swagger: "2.0"
info:
  description: This is a sample server Petstore server.
  version: "1.0.0"
  title: Swagger Petstore
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 10.156.74.170:9222
basePath: /customerribbon
schemes:
  - http
paths:
  /customerdetails:
    post:
      tags:
        - customerdetails
      summary: Get Customer Details
      description: ""
      operationId: addPet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Get Customer Details
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        "405":
          description: Invalid input

definitions:
  Pet:
    type: object
    # note! this is referenced but not defined
    
  CustomerSearchReq:
    type: object
    properties:
      responseType:
        type: string
        xml:
          attribute: true
      maxCorrelatedCustomers:
        type: string
        xml:
          attribute: true
      SearchCriteria:
        $ref: "#/definitions/SearchCriteria"
      SearchDateRange:
        $ref: "#/definitions/SearchDateRange"
      PaginationCount:
        type: string
  SearchCriteria:
    type: object
    properties:
      SearchCriteriaFilter:
        $ref: "#/definitions/SearchFilterCriteria"
  SearchFilterCriteria:
    type: object
    properties:
      SearchParamName:
        type: string
        example: CUSTID
      SearchParamValue:
        type: string
        example: ABCD
  SearchDateRange:
    type: object
    properties:
      RangeBasis:
        type: string
        example: SYSDATE
      RangeStart:
        type: string
        example: 90
      RangeEnd:
        type: string
        example: 90
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          $ref: "#/definitions/Tag"
      status:
        type: string
        description: pet status in the store
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
      complete:
        type: boolean
```
