### ISSUE TITLE
Number-Strings are displayed as number not as strings

### ISSUE THREAD

**Issue by marcuszierke** [swagger-api/swagger-editor#2380] opened 2021-01-19 13:12 UTC
I noticed today that numbers, that I want to have returned as strings, are not been displayed correctly colorwise in the editor. If I define the values via enums it works fine but as soon as I specify an example on my own it is displayed in the editor as a number value (I guess that's what the red color stands for).

I attached some screenshots to illustrate the problem (for compliance reasons I couldn't extend the viewport of the screenshot, sorry for that).

![Screenshot 2021-01-19 at 14 05 06](https://user-images.githubusercontent.com/23409802/105038522-b92c1900-5a5f-11eb-9fa3-a95e5be22a39.png)
![Screenshot 2021-01-19 at 14 05 16](https://user-images.githubusercontent.com/23409802/105038525-ba5d4600-5a5f-11eb-87d5-7f02dba4c85b.png)
![Screenshot 2021-01-19 at 14 05 22](https://user-images.githubusercontent.com/23409802/105038529-baf5dc80-5a5f-11eb-92c8-5641604524e8.png)
![Screenshot 2021-01-19 at 14 05 31](https://user-images.githubusercontent.com/23409802/105038533-bb8e7300-5a5f-11eb-9c17-d47b6399ee21.png)

### Q&A (please complete the following information)
 - OS: MacOS Catalina
 - Browser: chrome, firefox, safari
 - Version: latest for all
 - Method of installation: webbrowser
 - Swagger/OpenAPI version: Swagger 2.0

**Comment by hkosova** [comment] 2021-01-25 15:58
Numeric strings must be quoted in order to be treated as strings. E.g.
```yaml
score:
  type: string
  example: "8.84"   # <-----
```
or
```yaml
type: object
example: {
  "value": "Austria",
  "score": "8.84"   # <-----
}
```

**Comment by byrdman** [comment] 2021-01-27 16:24
I've noticed the same thing.  If you start your "number" with a 0 it will render correctly as a string.

`example: "001"`

correctly renders as
![image](https://user-images.githubusercontent.com/2364470/106020563-87cbd280-6089-11eb-86ae-834698180867.png)


But:
`example: "1001"`

renders as:
![image](https://user-images.githubusercontent.com/2364470/106020841-c9f51400-6089-11eb-9a2f-9e26363142af.png)

**Comment by hkosova** [comment] 2021-02-08 18:10
@marcuszierke @byrdman can you please check if the issue is still happening? A [similar issue](https://github.com/swagger-api/swagger-ui/pull/6872) was fixed in a recent release of Swagger Editor/UI.

**Comment by byrdman** [comment] 2021-02-08 22:18
> @marcuszierke @byrdman can you please check if the issue is still happening? A [similar issue](https://github.com/swagger-api/swagger-ui/pull/6872) was fixed in a recent release of Swagger Editor/UI.

It appears to be fixed!  Thanks.

**Closed** 2021-02-25 12:46 UTC
Labels: type: support
