### ISSUE TITLE
SwaggerEditor@next: Error while downloading resolved JSON/YAML

### ISSUE THREAD

**Issue by congjunhua** [swagger-api/swagger-editor#3972] opened 2023-03-22 17:17 UTC
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [chrome]
 - Version: [111.0.5563.64]
 - Method of installation: [web]
 - Swagger-Editor version: [next]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### Content & configuration

<img width="667" alt="image" src="https://user-images.githubusercontent.com/95909681/226984122-97ea8588-c8c9-4d33-8aad-6cbd1e077bae.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/95909681/226984275-a4dcf6ad-a643-4bbc-ab9d-9fc044a298b4.png">

Example Swagger/OpenAPI definition:

https://editor-next.swagger.io/?_ga=2.248466254.810872330.1679498150-1020076937.1673430773

### Describe the bug you're encountering

Download Resolved Json failed...

### To reproduce...

1. open https://editor-next.swagger.io/?_ga=2.248466254.810872330.1679498150-1020076937.1673430773
2. Click on File
3. Click Download Resolved Json

### Expected behavior

Download Successful

### Screenshots

👆

### Additional context or thoughts

`null`

**Comment by char0n** [comment] 2023-03-24 08:07
Hi @congjunhua,

Thanks for the report. Looking into the issue.

**Comment by char0n** [comment] 2023-03-24 09:37
Here is the actual error that causes the issue:

![image](https://user-images.githubusercontent.com/193286/227482644-305320bb-943f-49b7-b94d-b6af5b5a7d2f.png)

Looks like ApiDOM cannot match the definition to the dereference strategy. Investigating why...

**Comment by char0n** [comment] 2023-03-24 10:04
When I execute the related code in Node.js environment it works without issues. The issue is specific to webpack build fragments.

**Comment by char0n** [comment] 2023-03-24 10:40
The issue is in webpack alias: https://github.com/swagger-api/swagger-editor-cra/blob/main/packages/react-scripts/config/webpack.config.js#L406

This line should be

```
 '@swagger-api/apidom-reference$':
          '/node_modules/@swagger-api/apidom-reference/es/configuration/saturated.js',

**Comment by char0n** [comment] 2023-03-24 10:52
Fixed in https://github.com/swagger-api/swagger-editor/pull/3975

**Closed** 2023-03-24 11:11 UTC
Labels: type: upstream bug, swagger-editor@next
