### ISSUE TITLE
SwaggerGenerator via EnvironmentVariable

### ISSUE THREAD

**Issue by tsproesser** [swagger-api/swagger-editor#2127] opened 2020-03-29 13:21 UTC
Right now SwaggerEditor expects the Generator unter https://generator.swagger.io what makes it almost impossible to set up a clean local Docker environment. So please consume a variable setting a custom Generator if defined.

**Comment by tsproesser** [comment] 2020-03-29 13:33
https://github.com/swagger-api/swagger-editor/blob/master/src/index.js

defaults

**Comment by hkosova** [comment] 2020-03-29 15:18
Duplicate of #1488.

**Closed by hkosova** 2020-03-29 15:18 UTC
