### ISSUE TITLE
- $Ref in array items is not being labeled as an error

### ISSUE THREAD

**Issue by jonaslagoni** [swagger-api/swagger-editor#1538] opened 2017-10-27 10:48 UTC
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       |  Using the editor on swaggerhub
| How did you install Swagger-Editor? |  Using online version
| Which browser & version?            |  Chrome, version: 62.0.3202

So I was trying to figure out why I could not generate neither server or client, when the editor did not give me any errors. Therefor i did a little trial and error and found out that i "accidentally" wrote my ref when trying to define an array as: `- $ref: '#/definitions/Folder'`. Instead of the correct way `$ref: '#/definitions/Folder'`. I then tried to add "-" in front of other refs, which all seem to generate an error in the editor. I therefor wonder if this is intentional or a bug, either in the editor or code-generator?

This only seem to be an issue when generating certain types of servers and clients:

| Server                                  | Does it work?
| ----------------------------------- | -------
| Jaxrs              |  No
| Erlang-server       | Yes

| Client                                  | Does it work?
| ----------------------------------- | -------
| Java              |  No
| Android       | Yes

I did not test the rest of the possibilities.

### Demonstration API definition

This is the YAML file used

```yaml
swagger: "2.0"
info:
  description: "test"
  version: "0.1"
  title: "test"
paths:
  /folder/getFolderStructure:
    get:
      tags:
       - Folder Structure
      summary: Get the folder structure for the project
      description: ''
      operationId: getFolderStructure
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Get folder structure request
          required: true
          schema:
            $ref: '#/definitions/GetFolderStructureRequest'
      responses:
        '200':
          description: The folder structure of the project
          schema:
            $ref: '#/definitions/GetFolderStructureResponse'
definitions:
  GetFolderStructureResponse:
    type: object
    properties:
      folderStructure:
        type: array
        items:
            - $ref: '#/definitions/Folder'
  Folder:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      folderStructure:
        type: array
        items:
          - $ref: '#/definitions/Folder'
      fileStructure:
        type: array
        items:
          - $ref: '#/definitions/UploadedFile'
  GetFolderStructureRequest:
    type: object
    properties:
      id:
        type: integer
        format: int64
  UploadedFile:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The id the file has been given
      type:
        type: string
        description: The type of file it was
      dateTimeUploaded:
        type: string
        description: The datetime when it was uploaded
      dateTimeLastUpdated:
        type: string
        description: The datetime when it was updated last time
# Added by API Auto Mocking Plugin
host: "localhost:41003"
basePath: "/fms"
schemes:
 - http"
```

### Configuration (browser query string, constructor, config.yaml)
No configurations.

### Expected Behavior
The editor should highlight the error instead when trying to generate server or client, and not just being able to generate it for certain types of servers and clients.

### Current Behavior
The editor does not highlight the error, and when trying to generate certain types of server or client you are prompted with:
> There was an error generating the clients/server .... code. Please ensure that the spec is a valid definition.

### Possible Solution
Make the error appear before trying to generate a server/client, so the syntax have to be correct.

### Context

I had to trial and error my way through the methods and definitions before realizing that it was the arrays that somehow created an error. Then eventually I realized that the ref was written wrong.

**Comment by hkosova** [comment] 2017-10-31 10:01
@webron This looks like a duplicate of #1255 and #1132.

**Comment by shockey** [comment] 2018-05-22 05:30
Closing as a duplicate of #1255.

**Closed by shockey** 2018-05-22 05:30 UTC
Labels: P2, cat: validation, type: bug, version: 3.x
