### ISSUE TITLE
allOf does not work in the swagger-editor at all.

### ISSUE THREAD

**Issue by jameelg** [swagger-api/swagger-editor#387] opened 2015-03-28 02:47 UTC
When trying to use the Polymorphism example given in the swagger 2.0 spec. The swagger-editor complains with the following error: Data does not match any schemas from 'anyOf'

Example: 
```
definitions:
  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
    - type: object
      required:
      - rootCause
      properties:
        rootCause:
          type: string
```

**Comment by mohsen1** [comment] 2015-03-28 02:50
Duplicate of #272

**Comment by mohsen1** [comment] 2015-03-28 02:54
BTW you have indentation in `ExtendedErrorModel `

```
  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel' # <--- this should be indented on level in
    - type: object # <-- also this
      required:
      - rootCause
      properties:
        rootCause:
          type: string
```

**Comment by jameelg** [comment] 2015-03-28 09:43
Even with the correct indentation, the swagger-editor still barfs. I do not care of the editor does not render the allOf properties properly as stated in issue #272. Right now the problem is the swagger-editor gives me an error when trying to use polymorphism. It throws and Error and shows "Working..." at the top right of the screen. As soon as I as the second array item the javascript code throws an error. I don't think this is the same issue as #272. 

Are you not seeing this issue in the editor.swagger.io site?

```
Uncaught Error: ptr is required
d97315e0.vendor.js:22 b.exports.pathFromPointerd97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:8 $bd97315e0.vendor.js:8 Bed97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:8 ycd97315e0.vendor.js:8 Bcd97315e0.vendor.js:8 scd97315e0.vendor.js:8 Bed97315e0.vendor.js:22 xd97315e0.vendor.js:22 Fd97315e0.vendor.js:22 Gd97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:22 nd97315e0.vendor.js:22 Ad97315e0.vendor.js:22 hd97315e0.vendor.js:22 (anonymous function)d97315e0.vendor.js:22 Jd97315e0.vendor.js:22 Bd97315e0.vendor.js:22 Hd97315e0.vendor.js:22 I.validate79f6c15a.scripts.js:2 b79f6c15a.scripts.js:1 n79f6c15a.scripts.js:2 (anonymous function)79f6c15a.scripts.js:2 save79f6c15a.scripts.js:1 gd97315e0.vendor.js:8 e
```

**Comment by mohsen1** [comment] 2015-03-28 15:16
That's probably Swagger Tools issue. I believe it's this issue https://github.com/apigee-127/swagger-tools/issues/180

Please follow up with @whitlockjc in Swagger Tools repo

**Comment by freak4pc** [comment] 2015-04-16 12:03
This is also happening for me 

```
definitions:
  Response:
    type:             object
    required:
      - code
      - time
    properties:
      code: 
        type:         integer
        format:       int32
        minimum:      100
        maximum:      600
      time:
        type:         string
        format:       date-time
  StringResponse:
    allOf:
      - $ref:         '#/definitions/Response'
      - type:         object
        required: 
        - response
        properties:
          response:
            type:     string
```

Stuck with "Working" and console spits out
```
Uncaught Error: ptr is required
extensions::utils:93 Uncaught TypeError: Cannot read property 'impl' of undefined
```

**Comment by mohsen1** [comment] 2015-04-16 16:15
I think `ptr is required` error is already fixed in Swagger Tools. Today I'm going to update Swagger Tools so it will get fixed.

**Comment by freak4pc** [comment] 2015-04-16 17:05
That would be awesome :) does that mean it knows how to handle allOf now? (the tools I mea)

**Comment by mohsen1** [comment] 2015-04-16 17:12
The rendering of allOf is not fixed yet. Follow #272 for that.

**Comment by mohsen1** [comment] 2015-04-23 00:02
This is fixed.

**Closed by mohsen1** 2015-04-23 00:02 UTC
Labels: bug, duplicate
