### ISSUE TITLE
 Linter not highlighting correctly for multiline description

### ISSUE THREAD

**Issue by branlok** [swagger-api/swagger-editor#2972] opened 2022-03-15 02:38 UTC
### Q&A (please complete the following information)
M1X
Chrome Version  99.0.4844.51 
Installed by npm
Swagger  -  "version": "4.0.6",
OpenAPI 3.0

Everything in original setting.

![Screen Shot 2022-03-14 at 10 37 32 PM](https://user-images.githubusercontent.com/73308970/158294763-1dc6534f-0d3e-40b0-b702-7b5d4bce35da.png)

Example Swagger/OpenAPI definition:
```yaml
  /users/{userid}/likes:
    get:
      summary: Returns a user likes.
      description: |
        lint highlighter isn't working properly
        as shown below everything is highlighted green 
      tags:
        - Users
      parameters:
        - name: userid
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':    
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The user name.
```

**Comment by hkosova** [comment] 2022-03-15 06:59
Duplicate of #2828.

**Closed by hkosova** 2022-03-15 06:59 UTC
