### ISSUE TITLE
Editor - Import file UI

### ISSUE THREAD

**Issue by boyfox** [swagger-api/swagger-editor#1436] opened 2017-07-31 04:04 UTC
![screen shot 2017-07-28 at 5 49 29 pm](https://user-images.githubusercontent.com/3168694/28762361-4dbb65ae-75cf-11e7-9199-bbc7ad19218e.png)

**Comment by webron** [comment] 2017-07-31 04:10
?

**Comment by hkosova** [comment] 2017-07-31 08:13
Duplicate of #1413?

**Comment by shockey** [comment] 2017-08-03 21:56
Closing as a duplicate of #1413.

**Closed by shockey** 2017-08-03 21:56 UTC
