### ISSUE TITLE
Feature request - Namespace UI on swagger editor

### ISSUE THREAD

**Issue by kgrosvenor** [swagger-api/swagger-editor#1899] opened 2018-11-03 12:35 UTC
I like the new version swagger editor, but there is one feature which would top it all off in my opinion.

I think it would be really cool if you could give the namespace name, or a form to fill out before the client/server libraries download.

Let me know what you guys think 👍

**Comment by hkosova** [comment] 2019-08-12 12:34
Duplicate of #713.

**Closed by hkosova** 2019-08-12 12:34 UTC
Labels: cat: code generation, type: feature
