### ISSUE TITLE
separate html generation into separate node module

### ISSUE THREAD

**Issue by bendavis78** [swagger-api/swagger-editor#762] opened 2016-01-06 21:41 UTC
it would be nice to have a separate node module that just generates the API docs.

**Comment by simondean** [comment] 2016-01-18 17:06
Is this a duplicate of #664

**Comment by saharj** [comment] 2016-02-06 18:33
This is not inline with Swagger Editor goals. Feel free to fork and make your own module.

**Closed by saharj** 2016-02-06 18:33 UTC
