### ISSUE TITLE
not able to run swagger editor on localhost in windows 7

### ISSUE THREAD

**Issue by suretek** [swagger-api/swagger-editor#671] opened 2015-09-30 12:29 UTC

**Comment by suretek** [comment] 2015-09-30 12:33
not able to get dist folder inside swagger-editor which is required to run editor. While in swagger-ui it was there in clone for github. 
Even after running build command not able to get the same.
npm run build

please suggest what to do to create dist folder.
Thanks

**Comment by chrisdudley** [comment] 2015-09-30 12:52
As per the docs:

git clone https://github.com/swagger-api/swagger-editor.git
cd swagger-editor
npm start

**Comment by suretek** [comment] 2015-09-30 13:43
Hi Chris,

Thanks for your quick reply. I followed the same steps but after executing  "npm start" command I am not able to see "dist" folder inside swagger-editor folder, which is required to run editor.

while opening swagger-editor in brower using - http://localhost/swagger-editor it automatically changes to http://localhost/swagger-editor/dist

So as per my understanding there is some problem in execution of npm start command. 

Could you please give me latest build code for swagger-editor with "dist" folder.

Thanks
Subodh

  ----- Original Message -----

**Comment by chrisdudley** [comment] 2015-09-30 14:53
If you follow the instructions above it will automatically open a browser window pointing to something like: http://localhost:8080/
It just works - I just ran it myself (on windows 7).

Check the output of the npm start command - maybe there was some error there?
It doesn't just build the 'dist' folder, it stands up a webserver and runs it automatically.
I have never needed to manually point my web browser anywhere - the npm start command opens the browser tab for me.

**Comment by saharj** [comment] 2016-02-06 18:39
Duplicate of #743

**Closed by saharj** 2016-02-06 18:39 UTC
Labels: question
