### ISSUE TITLE
SwaggerEditor@next: apidom.worker.js & editor.worker.js 404 (Not found) SwaggerEditor@next + Vue 3

### ISSUE THREAD

**Issue by vitjaz** [swagger-api/swagger-editor#3816] opened 2023-02-07 09:39 UTC
### System
- OS: Windows 10 Pro 21H1 (build 19043.1466)
- Browser: Chrome (108.0.5359.125)
- Method of installation: ``npm``
- Swagger-Editor version: ``^5.0.0-alpha.44``

### Content & configuration
My idea is to create a simple version of [Stoplight](https://stoplight.io/) based on Vue 3 using the Swagger-Editor@Next component

Swagger/OpenAPI definition (from example):
```js
const url =
  "https://raw.githubusercontent.com/asyncapi/spec/v2.2.0/examples/streetlights-kafka.yml";
```

### My code base
``main.js``
```js
import { createApp } from "vue";
import App from "./App.vue";
import "./style.css";
const app = createApp(App);
self.MonacoEnvironment = {
  /**
   * We're building into the dist/ folder. When application starts on
   * URL=https://example.com then SwaggerEditor will look for
   * `apidom.worker.js` on https://example.com/dist/apidom.worker.js and
   * `editor.worker` on https://example.com/dist/editor.worker.js.
   */
  baseUrl: `${document.baseURI || location.href}dist/`,
};
app.mount("#swagger-editor");
```

``App.vue``
```vue
<template>
  <h1>My Vue app with Swagger Editor</h1>
  <SwaggerEditorPure :url="url" />
</template>

<script setup>
import { applyReactInVue, applyPureReactInVue } from "veaury";
import SwaggerEditor from "@swagger-api/swagger-editor";
import "./swagger-editor.css"; //I had to copy the styles to src because they weren't loaded
// import "@swagger-api/swagger-editor/swagger-editor.css";
const url =
  "https://raw.githubusercontent.com/asyncapi/spec/v2.2.0/examples/streetlights-kafka.yml";

const SwaggerEditorPure = applyPureReactInVue(SwaggerEditor);
</script>

<style>
</style>
```

``vue.config.js``
```js
const { defineConfig } = require("@vue/cli-service");
const path = require("path");
const webpack = require("webpack");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");
//const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    entry: {
      app: "./src/main.js",
      "apidom.worker": "@swagger-api/swagger-editor/apidom.worker",
      "editor.worker": "@swagger-api/swagger-editor/editor.worker",
    },
    output: {
      globalObject: "self",
      filename: "[name].js",
      path: path.resolve(__dirname, "dist"),
    },
    resolve: {
      extensions: ["", ".js", ".jsx", ".css"],
      modules: ["node_modules"],
      fallback: {
        path: false,
        fs: false,
        http: require.resolve("stream-http"), // required for asyncapi parser
        https: require.resolve("https-browserify"), // required for asyncapi parser
        stream: require.resolve("stream-browserify"),
        util: require.resolve("util"),
        zlib: false,
      },
      alias: {
        // This alias doesn't pull any languages into bundles and works as monaco-editor-core was installed
        "monaco-editor$": "monaco-editor/esm/vs/editor/edcore.main.js",
        // This alias make sure we don't pull two different versions of monaco-editor
        "monaco-editor": "/node_modules/monaco-editor",
      },
    },
    plugins: [
      new webpack.ProvidePlugin({
        process: "process/browser.js",
        Buffer: ["buffer", "Buffer"],
      }),
      new NodePolyfillPlugin(),
    ],
    experiments: {
      topLevelAwait: true,
    },
    module: {
      rules: [
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
          include: [path.resolve(__dirname, "not_exist_path")],
        },
        /**
         * The default way in which webpack loads wasm files won’t work in a worker,
         * so we will have to disable webpack’s default handling of wasm files and
         * then fetch the wasm file by using the file path that we get using file-loader.
         *
         * Resource: https://pspdfkit.com/blog/2020/webassembly-in-a-web-worker/
         *
         * Alternatively, WASM file can be bundled directly into JavaScript bundle as data URLs.
         * This configuration reduces the complexity of WASM file loading
         * but increases the overal bundle size:
         *
         * {
         *   test: /\.wasm$/,
         *   type: 'asset/inline',
         * }
         */
        {
          test: /\.wasm$/,
          loader: "file-loader",
          type: "javascript/auto", // this disables webpacks default handling of wasm
        },
      ],
    },
  },
});
```

``My deps``
```json
"dependencies": {
    "@mui/material": "^5.11.7",
    "@swagger-api/swagger-editor": "^5.0.0-alpha.44",
    "babel-preset-react-app": "^10.0.1",
    "core-js": "^3.8.3",
    "monaco-editor-webpack-plugin": "^7.0.1",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "swagger-ui-react": "^4.15.5",
    "veaury": "^2.3.11",
    "vue": "^3.2.13"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.3",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "file-loader": "^6.2.0",
    "https-browserify": "^1.0.0",
    "process": "^0.11.10",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "style-loader": "^3.3.1",
    "util": "^0.12.5"
  },
```
### My problem
My application builds and works, but the console gives errors and it seems that monaco-editor does not recognize the code (screenshots below)

### Screenshots
![image](https://user-images.githubusercontent.com/47814045/217206958-8fb17ebe-7325-4732-8ea9-f41d0cb240e1.png)

Console code:
```
GET http://localhost:8082/dist/apidom.worker.js 404 (Not Found)
GET http://localhost:8082/dist/editor.worker.js 404 (Not Found)
react_devtools_backend.js:4012 [main 2023-02-07T09:34:21.124Z] [monaco] provider FAILED
[main 2023-02-07T09:34:21.125Z] Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (VM115076 editorSimpleWorker.js:543:27)
    at eval (webWorker.js?96c9:38:1)
VM114407 errors.js:31 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?f794:463:1)
    at eval (webWorker.js?96c9:38:1)
    at eval (VM114407 errors.js:31:17)
```

Please, tell me what could be the problem? Maybe I need to knock on the monaco-editor repository?

**Comment by char0n** [comment] 2023-02-09 15:55
The issue is with your webpack configuration. You told swagger editor SwaggerEditor@5 to look for workers at: 

```
baseUrl: `${document.baseURI || location.href}dist/`,
```

But when SwaggerEditor@5 wants to access workers there by requesting ` http://localhost:8082/dist/apidom.worker.js`, this url returns `404`. You have to make sure that your webpack build fragments are accessible.

**Comment by char0n** [comment] 2023-02-14 09:22
Closing as support has been provided and it looks like tooling configuration related issue and not issue with SwaggerEditor.

**Closed by char0n** 2023-02-14 09:22 UTC
Labels: type: support, swagger-editor@next
