### ISSUE TITLE
Semantic error at paths

### ISSUE THREAD

**Issue by gitforpushpak** [swagger-api/swagger-editor#1617] opened 2018-01-03 06:12 UTC
Hi,

I am seeing below error when I import my json into the https://app.swaggerhub.com
### swagger: '2.0'
```
Semantic error at paths./{baseSiteId}/{lang}/{areaCode}/users/{userId}/customergroups
Declared path parameter "baseSiteId" needs to be defined as a path parameter at either the path or operation level
```
my controller has the above mapping.

/{baseSiteId}/{lang}/{areaCode}/users/{userId}/customergroups
How can I fix this issue ?

thanks.

**Comment by shockey** [comment] 2018-01-03 06:20
Hi @gitforpushpak!

This is a known bug (https://github.com/swagger-api/swagger-editor/issues/1614) that was introduced by our new validation system last week.

I expect to have this patched within the next day or two, and have a fix released this Friday. SwaggerHub will need to pick the changes up though, you'd need to ask them when they have a release scheduled that will include it.

**Comment by gitforpushpak** [comment] 2018-01-03 19:55
@shockey thanks for the reply. Once you have the patch ready, what should I do ? How it will resolve my error? Can you please explain me?

**Comment by shockey** [comment] 2018-01-05 06:48
@gitforpushpak, if you're using SwaggerHub you'll need to wait until the SwaggerHub team updates their service to use the latest version of Swagger-Editor - there's no way for you as a user to swap out the version used within SwaggerHub.

The fix I'm about to merge into our master branch changes the data going into the path item validator, so that $ref'd parameters are correctly taken into account.

(cc: @ponelat)

**Comment by shockey** [comment] 2018-01-05 06:55
I closed this as the issue is resolved on our end, but feel free to reply if you have any lingering questions @gitforpushpak!

**Closed** 2018-01-05 06:55 UTC
Labels: Support
