### ISSUE TITLE
Google Drive Support

### ISSUE THREAD

**Issue by kurtuluso** [swagger-api/swagger-editor#303] opened 2015-01-22 12:20 UTC
Do you thinking of implementing  importing from and writing to Google Drive file?
It is very good to edit the swagger file online but I can not save the file on cloud.
This is very important I think.
I'm really trying to find a way for opening, saving and editing online

**Comment by mohsen1** [comment] 2015-01-22 17:53
We are working on having a backend and saving Swagger documents for you. Very similiar to JSBin or PasteBin

**Comment by kurtuluso** [comment] 2015-01-25 16:39
But the need for private cloud account stills.
Google drive has a system for external editors initiated from google drive.
On the other hand, it is widely used by everyone. Just you have to integrate it with swagger editor.

**Comment by mohsen1** [comment] 2015-01-27 21:54
Dupe of #174

**Closed by mohsen1** 2015-01-27 21:54 UTC
Labels: Backend, duplicate, enhancement
