### ISSUE TITLE
😱 Could not render _, see the console.

### ISSUE THREAD

**Issue by vitjaz** [swagger-api/swagger-editor#3797] opened 2023-02-02 12:27 UTC
### System
 - OS: Windows 10 Pro 21H1 (build 19043.1466) 
 - Browser: Chrome (108.0.5359.125)
 - Method of installation: npm
 - Swagger-Editor version: ^5.0.0-alpha.15

Example Swagger/OpenAPI definition:
```yaml
https://raw.githubusercontent.com/asyncapi/spec/v2.2.0/examples/streetlights-kafka.yml
```

index.js
```js
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";

const root = ReactDOM.createRoot(document.getElementById("root"));

window.self.MonacoEnvironment = {
  /**
   * We're building into the dist/ folder. When application starts on
   * URL=https://example.com then SwaggerEditor will look for
   * `apidom.worker.js` on https://example.com/dist/apidom.worker.js and
   * `editor.worker` on https://example.com/dist/editor.worker.js.
   */
  baseUrl: `${document.baseURI || window.location.href}/dist/`,
};
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

App.js 
```js
import "./App.css";
import SwaggerEditor from "@swagger-api/swagger-editor";
import "@swagger-api/swagger-editor/swagger-editor.css";

const url =
  "https://raw.githubusercontent.com/asyncapi/spec/v2.2.0/examples/streetlights-kafka.yml";
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>My React App with Swagger editor</p>
        <SwaggerEditor url={url} />
      </header>
    </div>
  );
}

export default App;
```

craco.config.js
```js
const path = require("path");
const webpack = require("webpack");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

module.exports = {
  webpack: {
    entry: {
      app: "./index.js",
      "apidom.worker": "@swagger-api/swagger-editor/apidom.worker",
      "editor.worker": "@swagger-api/swagger-editor/editor.worker",
    },
    output: {
      globalObject: "self",
      filename: "[name].js",
      path: path.resolve(__dirname, "dist"),
    },
    resolve: {
      fallback: {
        path: false,
        fs: false,
        http: require.resolve("stream-http"), // required for asyncapi parser
        https: require.resolve("https-browserify"), // required for asyncapi parser
        stream: require.resolve("stream-browserify"),
        util: require.resolve("util"),
        zlib: false,
      },
      alias: {
        // This alias doesn't pull any languages into bundles and works as monaco-editor-core was installed
        "monaco-editor$": "monaco-editor/esm/vs/editor/edcore.main.js",
        // This alias make sure we don't pull two different versions of monaco-editor
        "monaco-editor": "/node_modules/monaco-editor",
      },
    },
    plugins: [
      new webpack.ProvidePlugin({
        process: "process/browser.js",
        Buffer: ["buffer", "Buffer"],
      }),
      new NodePolyfillPlugin(),
    ],
    module: {
      rules: [
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
        },
        /**
         * The default way in which webpack loads wasm files won’t work in a worker,
         * so we will have to disable webpack’s default handling of wasm files and
         * then fetch the wasm file by using the file path that we get using file-loader.
         *
         * Resource: https://pspdfkit.com/blog/2020/webassembly-in-a-web-worker/
         *
         * Alternatively, WASM file can be bundled directly into JavaScript bundle as data URLs.
         * This configuration reduces the complexity of WASM file loading
         * but increases the overal bundle size:
         *
         * {
         *   test: /\.wasm$/,
         *   type: 'asset/inline',
         * }
         */
        {
          test: /\.wasm$/,
          loader: "file-loader",
          type: "javascript/auto", // this disables webpacks default handling of wasm
        },
      ],
    },
  },
};
```

### My Error
When I try to start my app with ``npm start`` i have 
```js
😱 Could not render _, see the console.
```
### In Console I have
```js
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
The above error occurred in the <_> component:
```

![image](https://user-images.githubusercontent.com/47814045/216325008-bc39f17c-8c97-4ac5-b1f2-958d33d9ef76.png)

### To reproduce...
1. Create react app with CRA
2. Inject CRACO for webpack configuration and change ``start`` script to ``craco start --config ./craco.config.js``
3. Config webpack with guide of swagger/next branch
5. Add ``NodePolyfillPlugin`` for polyfill webpack 4 resolves to webpack 5
6. run ``npm start`` and see this error

### My deps
```js
"dependencies": {
    "@swagger-api/swagger-editor": "^5.0.0-alpha.15",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

### My dev deps
```js
"devDependencies": {
    "@craco/craco": "^7.0.0",
    "https-browserify": "^1.0.0",
    "process": "^0.11.10",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "util": "^0.12.5"
  }
```

**Comment by char0n** [comment] 2023-02-09 16:09
Closing as duplicate of https://github.com/swagger-api/swagger-editor/issues/3796

**Closed by char0n** 2023-02-09 16:09 UTC
