### ISSUE TITLE
useBackendForStorage not issuing PUTs

### ISSUE THREAD

**Issue by jadbox** [swagger-api/swagger-editor#598] opened 2015-08-24 03:27 UTC
When I useBackendForStorage to true with swagger-editor 2.9.6, I see that a GET request is made from editor/spec but never a PUT/POST to save changes. I've even looked at my browser network logs and found that the editor is never attempting to save... even though I get the successful validation notification popup (in the top corner) when changes are made.

**Comment by jadbox** [comment] 2015-08-24 03:27
Config:

{
  "codegen": {
    "clients": "http://generator.swagger.io/api/gen/clients",
    "client": "http://generator.swagger.io/api/gen/clients/{language}"
  },
  "analytics": {
    "google": {
        "id": -1
      }
    },
  "disableCodeGen": false,
  "examplesFolder": "/",
  "editorOptions": {
    "theme": "ace/theme/atom_dark"
  },
  "exampleFiles": [],
  "autocompleteExtension": {},
  "useBackendForStorage": true,
  "backendThrottle": 200,
  "backendEndpoint": "/editor/spec",
  "backendHealthCheckTimeout": 5000,
  "useYamlBackend": false,
  "disableFileMenu": false,
  "headerBranding": false,
  "enableTryIt": true,
  "brandingCssClass": "",
  "enableBackendHealthCheck": false,
  "backendHealthCheckTimeout": -1
}

**Comment by mohsen1** [comment] 2015-08-24 06:23
Duplicate of #592

**Comment by jadbox** [comment] 2015-08-24 20:53
@mohsen1 I don't think this is a duplicate because the middleware doesn't error and I don't even see from the browser's perspective ANY call to PUT data for /editor/spec.

**Comment by gietl** [comment] 2015-08-27 16:46
@jadbox I am seeing the same thing when having useYamlBackend set to false. If it's set to true, it will successfully send a PUT, but then the data is in yaml format and not json.

**Closed** 2015-09-16 00:26 UTC
Labels: backend, bug, duplicate

**Comment by jadbox** [comment] 2015-09-16 02:26
@gietl Confirmed... setting useYamlBackend to True allows backend saving.
