### ISSUE TITLE
Enum ref failing in query parameter

### ISSUE THREAD

**Issue by kaungst** [swagger-api/swagger-editor#428] opened 2015-05-06 06:22 UTC
I'm unable to get a reference to a predefined enum object in params. Looks like it might have to do with $ref needing to be nested in an object and enum: only accepting array elements/parameters being a list of objects/nowhere to nest the ref?

Would this be a feature request or is it a bug?

A failing example taken from the swagger editor
---EDIT--- switched from YAML to JSON
---EDIT--- I suck at markdown
```json
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "PetStore on Heroku"
    },
    "host": "petstore-api.herokuapp.com",
    "basePath": "/pet",
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json",
        "text/xml"
    ],
    "produces": [
        "application/json",
        "text/html"
    ],
    "paths": {
        "/": {
            "get": {
                "parameters": [
                    {
                        "name": "pet_color",
                        "in": "query",
                        "description": "a pet color",
                        "type": "integer",
                        "enum": {
                            "$ref": "#/definitions/PET_COLORS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List all pets",
                        "schema": {
                            "title": "Pets",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Pet"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Pet": {
            "properties": {
                "name": {
                    "type": "string"
                },
                "pet_enums": {
                    "$ref": "#/definitions/PET_COLORS"
                }
            }
        },
        "PET_COLORS": {
            "description": "A pet's color",
            "type": "integer",
            "enum": [
                "green",
                "purple",
                "blue"
            ]
        }
    }
}
```

**Comment by webron** [comment] 2015-05-06 06:49
It would be neither. It's not a bug since it's not supported but the Swagger spec. It's not a feature, since... it's not supported by the spec :) It could be a feature request for the spec, but that won't be implemented soon.

Also, a type `integer` with an enum of strings would validate... nothing :)

**Comment by kaungst** [comment] 2015-05-06 06:57
bring up some interesting points.

I agree with them all!
I didn't know if it was something that was missed in the spec, though it also didn't look like it was built out in the source for the editor. I will add it as a feature request to the spec. As a curious point, any insight into why this wasn't considered important? Seems pretty useful, but I only have my use case, and I would guess it's fairly small?

still trying rectify the fact that enums have 'names' but they are really integers

**Comment by kaungst** [comment] 2015-05-06 06:57
side point, feel free to close this issue

**Comment by webron** [comment] 2015-05-06 07:04
There have been discussions about simplifying it, but there are a few complications around it.
FWIW, we're probably not going to add $ref's for enums because that's just not standard in JSON Schema.

You /can/ ease up some of the repetitions if you need to define the same parameter over and over again, but you would still have to define the enum explicitly at least once for a given parameter (unless it is a body parameter).

**Closed by webron** 2015-05-06 07:04 UTC
